//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

using System.ComponentModel;
using System.Runtime.Serialization;
using Miaow.Domain.Dto.Validate;


namespace Miaow.Domain.Dto
{
    ////
    //using System.ComponentModel;
    //////using System.Runtime.Serialization;
    //
    /// <summary>
    /// m_group_type_info
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(m_group_type_infoDtoValidate))]
    public partial class m_group_type_infoDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// group_type_id
        /// </summary>
    	[DataMember]
    	[DisplayName("group_type_id")]
        public virtual string group_type_id
        {
            get;
            set;
        }
    
        /// <summary>
        /// group_type_name
        /// </summary>
    	[DataMember]
    	[DisplayName("group_type_name")]
        public virtual string group_type_name
        {
            get;
            set;
        }
    
        /// <summary>
        /// created_time
        /// </summary>
    	[DataMember]
    	[DisplayName("created_time")]
        public virtual System.DateTime created_time
        {
            get;
            set;
        }
    
        /// <summary>
        /// updated_time
        /// </summary>
    	[DataMember]
    	[DisplayName("updated_time")]
        public virtual Nullable<System.DateTime> updated_time
        {
            get;
            set;
        }
    
        /// <summary>
        /// deleted
        /// </summary>
    	[DataMember]
    	[DisplayName("deleted")]
        public virtual Nullable<int> deleted
        {
            get;
            set;
        }
    
        /// <summary>
        /// deleted_time
        /// </summary>
    	[DataMember]
    	[DisplayName("deleted_time")]
        public virtual Nullable<System.DateTime> deleted_time
        {
            get;
            set;
        }

        #endregion

    }
}
