//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

using System.ComponentModel;
using System.Runtime.Serialization;
using Miaow.Domain.Dto.Validate;


namespace Miaow.Domain.Dto
{
    ////
    //using System.ComponentModel;
    //////using System.Runtime.Serialization;
    //
    /// <summary>
    /// m_profile_info
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(m_profile_infoDtoValidate))]
    public partial class m_profile_infoDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// profile_id
        /// </summary>
    	[DataMember]
    	[DisplayName("profile_id")]
        public virtual string profile_id
        {
            get;
            set;
        }
    
        /// <summary>
        /// user_id
        /// </summary>
    	[DataMember]
    	[DisplayName("user_id")]
        public virtual string user_id
        {
            get;
            set;
        }
    
        /// <summary>
        /// profile_image_url
        /// </summary>
    	[DataMember]
    	[DisplayName("profile_image_url")]
        public virtual string profile_image_url
        {
            get;
            set;
        }
    
        /// <summary>
        /// createdtime
        /// </summary>
    	[DataMember]
    	[DisplayName("createdtime")]
        public virtual System.DateTime createdtime
        {
            get;
            set;
        }

        #endregion

    }
}
