//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

using System.ComponentModel;
using System.Runtime.Serialization;
using Miaow.Domain.Dto.Validate;


namespace Miaow.Domain.Dto
{
    ////
    //using System.ComponentModel;
    //////using System.Runtime.Serialization;
    //
    /// <summary>
    /// m_user_index_info
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(m_user_index_infoDtoValidate))]
    public partial class m_user_index_infoDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// user_id
        /// </summary>
    	[DataMember]
    	[DisplayName("user_id")]
        public virtual int user_id
        {
            get;
            set;
        }
    
        /// <summary>
        /// user_name
        /// </summary>
    	[DataMember]
    	[DisplayName("user_name")]
        public virtual string user_name
        {
            get;
            set;
        }
    
        /// <summary>
        /// msg_count
        /// </summary>
    	[DataMember]
    	[DisplayName("msg_count")]
        public virtual Nullable<int> msg_count
        {
            get;
            set;
        }
    
        /// <summary>
        /// fans_count
        /// </summary>
    	[DataMember]
    	[DisplayName("fans_count")]
        public virtual Nullable<int> fans_count
        {
            get;
            set;
        }
    
        /// <summary>
        /// follow_count
        /// </summary>
    	[DataMember]
    	[DisplayName("follow_count")]
        public virtual Nullable<int> follow_count
        {
            get;
            set;
        }

        #endregion

    }
}
