//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

using System.ComponentModel;
using System.Runtime.Serialization;
using Miaow.Domain.Dto.Validate;


namespace Miaow.Domain.Dto
{
    ////
    //using System.ComponentModel;
    //////using System.Runtime.Serialization;
    //
    /// <summary>
    /// m_user_info
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(m_user_infoDtoValidate))]
    public partial class m_user_infoDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// user_id
        /// </summary>
    	[DataMember]
    	[DisplayName("user_id")]
        public virtual string user_id
        {
            get;
            set;
        }
    
        /// <summary>
        /// profile_id
        /// </summary>
    	[DataMember]
    	[DisplayName("profile_id")]
        public virtual int profile_id
        {
            get;
            set;
        }
    
        /// <summary>
        /// user_name
        /// </summary>
    	[DataMember]
    	[DisplayName("user_name")]
        public virtual string user_name
        {
            get;
            set;
        }
    
        /// <summary>
        /// password
        /// </summary>
    	[DataMember]
    	[DisplayName("password")]
        public virtual string password
        {
            get;
            set;
        }
    
        /// <summary>
        /// oldpassword
        /// </summary>
    	[DataMember]
    	[DisplayName("oldpassword")]
        public virtual string oldpassword
        {
            get;
            set;
        }
    
        /// <summary>
        /// email
        /// </summary>
    	[DataMember]
    	[DisplayName("email")]
        public virtual string email
        {
            get;
            set;
        }
    
        /// <summary>
        /// gender
        /// </summary>
    	[DataMember]
    	[DisplayName("gender")]
        public virtual string gender
        {
            get;
            set;
        }
    
        /// <summary>
        /// createdtime
        /// </summary>
    	[DataMember]
    	[DisplayName("createdtime")]
        public virtual System.DateTime createdtime
        {
            get;
            set;
        }
    
        /// <summary>
        /// updatedtime
        /// </summary>
    	[DataMember]
    	[DisplayName("updatedtime")]
        public virtual Nullable<System.DateTime> updatedtime
        {
            get;
            set;
        }
    
        /// <summary>
        /// C_remark
        /// </summary>
    	[DataMember]
    	[DisplayName("C_remark")]
        public virtual string C_remark
        {
            get;
            set;
        }
    
        /// <summary>
        /// location
        /// </summary>
    	[DataMember]
    	[DisplayName("location")]
        public virtual string location
        {
            get;
            set;
        }
    
        /// <summary>
        /// netaddress
        /// </summary>
    	[DataMember]
    	[DisplayName("netaddress")]
        public virtual string netaddress
        {
            get;
            set;
        }
    
        /// <summary>
        /// state
        /// </summary>
    	[DataMember]
    	[DisplayName("state")]
        public virtual int state
        {
            get;
            set;
        }
    
        /// <summary>
        /// user_sexual_orientation
        /// </summary>
    	[DataMember]
    	[DisplayName("user_sexual_orientation")]
        public virtual string user_sexual_orientation
        {
            get;
            set;
        }
    
        /// <summary>
        /// user_relationship_status
        /// </summary>
    	[DataMember]
    	[DisplayName("user_relationship_status")]
        public virtual string user_relationship_status
        {
            get;
            set;
        }
    
        /// <summary>
        /// birthday
        /// </summary>
    	[DataMember]
    	[DisplayName("birthday")]
        public virtual Nullable<System.DateTime> birthday
        {
            get;
            set;
        }
    
        /// <summary>
        /// blood_type
        /// </summary>
    	[DataMember]
    	[DisplayName("blood_type")]
        public virtual string blood_type
        {
            get;
            set;
        }
    
        /// <summary>
        /// blogs_url
        /// </summary>
    	[DataMember]
    	[DisplayName("blogs_url")]
        public virtual string blogs_url
        {
            get;
            set;
        }
    
        /// <summary>
        /// MSN
        /// </summary>
    	[DataMember]
    	[DisplayName("MSN")]
        public virtual string MSN
        {
            get;
            set;
        }
    
        /// <summary>
        /// QQ
        /// </summary>
    	[DataMember]
    	[DisplayName("QQ")]
        public virtual string QQ
        {
            get;
            set;
        }

        #endregion

    }
}
