//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// Sys_SightInfo
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_SightInfoDtoValidate))]
    public partial class Sys_SightInfoDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// 景区ID
        /// </summary>
    	[DataMember]
    	[DisplayName("景区ID")]
        public virtual int ParkID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 标题
        /// </summary>
    	[DataMember]
    	[DisplayName("标题")]
        public virtual string Title
        {
            get;
            set;
        }
    
        /// <summary>
        /// 分类ID
        /// </summary>
    	[DataMember]
    	[DisplayName("分类ID")]
        public virtual int ClassID
        {
            get { return _classID; }
            set
            {
                if (_classID != value)
                {
                    _classID = value;
                }
            }
        }
        private int _classID;
    
        /// <summary>
        /// 适合人群
        /// </summary>
    	[DataMember]
    	[DisplayName("适合人群")]
        public virtual string FitCrowd
        {
            get;
            set;
        }
    
        /// <summary>
        /// 说明
        /// </summary>
    	[DataMember]
    	[DisplayName("说明")]
        public virtual string Remark
        {
            get;
            set;
        }
    
        /// <summary>
        /// 景区网址
        /// </summary>
    	[DataMember]
    	[DisplayName("景区网址")]
        public virtual string Url
        {
            get;
            set;
        }
    
        /// <summary>
        /// 文件URL
        /// </summary>
    	[DataMember]
    	[DisplayName("文件URL")]
        public virtual string FileUrl
        {
            get;
            set;
        }
    
        /// <summary>
        /// 推荐指数
        /// </summary>
    	[DataMember]
    	[DisplayName("推荐指数")]
        public virtual double VoIndex
        {
            get;
            set;
        }
    
        /// <summary>
        /// 惊险指数
        /// </summary>
    	[DataMember]
    	[DisplayName("惊险指数")]
        public virtual double AdIndex
        {
            get;
            set;
        }
    
        /// <summary>
        /// 点击数
        /// </summary>
    	[DataMember]
    	[DisplayName("点击数")]
        public virtual int ViCount
        {
            get;
            set;
        }
    
        /// <summary>
        /// 标签
        /// </summary>
    	[DataMember]
    	[DisplayName("标签")]
        public virtual string Tag
        {
            get;
            set;
        }
    
        /// <summary>
        /// 最佳旅游时间
        /// </summary>
    	[DataMember]
    	[DisplayName("最佳旅游时间")]
        public virtual string OpToTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// logo 图片ID
        /// </summary>
    	[DataMember]
    	[DisplayName("logo 图片ID")]
        public virtual Nullable<int> PicID
        {
            get;
            set;
        }
    
        /// <summary>
        /// logo图片相对地址
        /// </summary>
    	[DataMember]
    	[DisplayName("logo图片相对地址")]
        public virtual string PicPath
        {
            get;
            set;
        }
    
        /// <summary>
        /// 视频ID
        /// </summary>
    	[DataMember]
    	[DisplayName("视频ID")]
        public virtual Nullable<int> VideoID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 视频绝对URL
        /// </summary>
    	[DataMember]
    	[DisplayName("视频绝对URL")]
        public virtual string VideoPath
        {
            get;
            set;
        }
    
        /// <summary>
        /// 评论条数
        /// </summary>
    	[DataMember]
    	[DisplayName("评论条数")]
        public virtual Nullable<int> CommCount
        {
            get;
            set;
        }
    
        /// <summary>
        /// 不尽人意
        /// </summary>
    	[DataMember]
    	[DisplayName("不尽人意")]
        public virtual string Blemish
        {
            get;
            set;
        }
    
        /// <summary>
        /// 省
        /// </summary>
    	[DataMember]
    	[DisplayName("省")]
        public virtual string Province
        {
            get;
            set;
        }
    
        /// <summary>
        /// 城市
        /// </summary>
    	[DataMember]
    	[DisplayName("城市")]
        public virtual string City
        {
            get;
            set;
        }
    
        /// <summary>
        /// 是在那个景区 大多和标题一样
        /// </summary>
    	[DataMember]
    	[DisplayName("是在那个景区 大多和标题一样")]
        public virtual string InSource
        {
            get;
            set;
        }
    
        /// <summary>
        /// 操作人
        /// </summary>
    	[DataMember]
    	[DisplayName("操作人")]
        public virtual string InAuthor
        {
            get;
            set;
        }
    
        /// <summary>
        /// 操作人ID
        /// </summary>
    	[DataMember]
    	[DisplayName("操作人ID")]
        public virtual int UserID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 添加时间
        /// </summary>
    	[DataMember]
    	[DisplayName("添加时间")]
        public virtual System.DateTime AddTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// Aud
        /// </summary>
    	[DataMember]
    	[DisplayName("Aud")]
        public virtual int Aud
        {
            get;
            set;
        }
    
        /// <summary>
        /// Generalize
        /// </summary>
    	[DataMember]
    	[DisplayName("Generalize")]
        public virtual int Generalize
        {
            get;
            set;
        }
    
        /// <summary>
        /// GeBeTime
        /// </summary>
    	[DataMember]
    	[DisplayName("GeBeTime")]
        public virtual Nullable<System.DateTime> GeBeTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// GeEnTime
        /// </summary>
    	[DataMember]
    	[DisplayName("GeEnTime")]
        public virtual Nullable<System.DateTime> GeEnTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 权重数
        /// </summary>
    	[DataMember]
    	[DisplayName("权重数")]
        public virtual double MeIndex
        {
            get;
            set;
        }
    
        /// <summary>
        /// 是否被删除 也可以理解为是否显示
        /// </summary>
    	[DataMember]
    	[DisplayName("是否被删除 也可以理解为是否显示")]
        public virtual int IsDelete
        {
            get;
            set;
        }
    
        /// <summary>
        /// 删除时间
        /// </summary>
    	[DataMember]
    	[DisplayName("删除时间")]
        public virtual Nullable<System.DateTime> DeTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 一句话评论
        /// </summary>
    	[DataMember]
    	[DisplayName("一句话评论")]
        public virtual string OneSentence
        {
            get;
            set;
        }
    
        /// <summary>
        /// 交通路线
        /// </summary>
    	[DataMember]
    	[DisplayName("交通路线")]
        public virtual string TrafficClew
        {
            get;
            set;
        }
    
        /// <summary>
        /// 电话
        /// </summary>
    	[DataMember]
    	[DisplayName("电话")]
        public virtual string Telephone
        {
            get;
            set;
        }
    
        /// <summary>
        /// 邮箱
        /// </summary>
    	[DataMember]
    	[DisplayName("邮箱")]
        public virtual string Email
        {
            get;
            set;
        }
    
        /// <summary>
        /// 传真
        /// </summary>
    	[DataMember]
    	[DisplayName("传真")]
        public virtual string Fax
        {
            get;
            set;
        }
    
        /// <summary>
        /// 视频截图
        /// </summary>
    	[DataMember]
    	[DisplayName("视频截图")]
        public virtual string VideoImg
        {
            get;
            set;
        }
    
        /// <summary>
        /// AudTime
        /// </summary>
    	[DataMember]
    	[DisplayName("AudTime")]
        public virtual Nullable<System.DateTime> AudTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// Boost
        /// </summary>
    	[DataMember]
    	[DisplayName("Boost")]
        public virtual Nullable<double> Boost
        {
            get;
            set;
        }
    
        /// <summary>
        /// 营业时间
        /// </summary>
    	[DataMember]
    	[DisplayName("营业时间")]
        public virtual string ShopHours
        {
            get;
            set;
        }
    
        /// <summary>
        /// 去过的
        /// </summary>
    	[DataMember]
    	[DisplayName("去过的")]
        public virtual Nullable<int> GoCount
        {
            get;
            set;
        }
    
        /// <summary>
        /// 想去的
        /// </summary>
    	[DataMember]
    	[DisplayName("想去的")]
        public virtual Nullable<int> WantCount
        {
            get;
            set;
        }
    
        /// <summary>
        /// IsRegister
        /// </summary>
    	[DataMember]
    	[DisplayName("IsRegister")]
        public virtual Nullable<int> IsRegister
        {
            get;
            set;
        }
    
        /// <summary>
        /// 导游图
        /// </summary>
    	[DataMember]
    	[DisplayName("导游图")]
        public virtual string ParkMap
        {
            get;
            set;
        }
    
        /// <summary>
        /// 停车场
        /// </summary>
    	[DataMember]
    	[DisplayName("停车场")]
        public virtual string ParkingSpace
        {
            get;
            set;
        }
    
        /// <summary>
        /// 景区地址
        /// </summary>
    	[DataMember]
    	[DisplayName("景区地址")]
        public virtual string Address
        {
            get;
            set;
        }
    
        /// <summary>
        /// 没有怎么用
        /// </summary>
    	[DataMember]
    	[DisplayName("没有怎么用")]
        public virtual Nullable<int> YesWantCount
        {
            get;
            set;
        }
    
        /// <summary>
        /// YesGoCount
        /// </summary>
    	[DataMember]
    	[DisplayName("YesGoCount")]
        public virtual Nullable<int> YesGoCount
        {
            get;
            set;
        }
    
        /// <summary>
        /// YesViCount
        /// </summary>
    	[DataMember]
    	[DisplayName("YesViCount")]
        public virtual Nullable<int> YesViCount
        {
            get;
            set;
        }
    
        /// <summary>
        /// SiteUrl
        /// </summary>
    	[DataMember]
    	[DisplayName("SiteUrl")]
        public virtual string SiteUrl
        {
            get;
            set;
        }
    
        /// <summary>
        /// Popularity
        /// </summary>
    	[DataMember]
    	[DisplayName("Popularity")]
        public virtual Nullable<int> Popularity
        {
            get;
            set;
        }
    
        /// <summary>
        /// 纬度
        /// </summary>
    	[DataMember]
    	[DisplayName("纬度")]
        public virtual Nullable<double> Latitude
        {
            get;
            set;
        }
    
        /// <summary>
        /// 经度
        /// </summary>
    	[DataMember]
    	[DisplayName("经度")]
        public virtual Nullable<double> Longitude
        {
            get;
            set;
        }
    
        /// <summary>
        /// 二级域名开头/其实是拼音
        /// </summary>
    	[DataMember]
    	[DisplayName("二级域名开头/其实是拼音")]
        public virtual string PY
        {
            get;
            set;
        }
    
        /// <summary>
        /// 周边酒店ID
        /// </summary>
    	[DataMember]
    	[DisplayName("周边酒店ID")]
        public virtual string CirHotelID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 周边景区ID
        /// </summary>
    	[DataMember]
    	[DisplayName("周边景区ID")]
        public virtual string CirParkID
        {
            get;
            set;
        }
    
        /// <summary>
        /// CommHtml
        /// </summary>
    	[DataMember]
    	[DisplayName("CommHtml")]
        public virtual Nullable<bool> CommHtml
        {
            get;
            set;
        }
    
        /// <summary>
        /// 门票
        /// </summary>
    	[DataMember]
    	[DisplayName("门票")]
        public virtual Nullable<int> Ticket
        {
            get;
            set;
        }
    
        /// <summary>
        /// 推荐人数
        /// </summary>
    	[DataMember]
    	[DisplayName("推荐人数")]
        public virtual Nullable<int> VouchCount
        {
            get;
            set;
        }
    
        /// <summary>
        /// 推荐总值
        /// </summary>
    	[DataMember]
    	[DisplayName("推荐总值")]
        public virtual Nullable<int> VouchValue
        {
            get;
            set;
        }
    
        /// <summary>
        /// 区码（0755，深圳）
        /// </summary>
    	[DataMember]
    	[DisplayName("区码（0755，深圳）")]
        public virtual string AreaCode
        {
            get;
            set;
        }
    
        /// <summary>
        /// IsShort
        /// </summary>
    	[DataMember]
    	[DisplayName("IsShort")]
        public virtual Nullable<int> IsShort
        {
            get;
            set;
        }
    
        /// <summary>
        /// IsSort
        /// </summary>
    	[DataMember]
    	[DisplayName("IsSort")]
        public virtual Nullable<int> IsSort
        {
            get;
            set;
        }
    
        /// <summary>
        /// SortProv
        /// </summary>
    	[DataMember]
    	[DisplayName("SortProv")]
        public virtual string SortProv
        {
            get;
            set;
        }
    
        /// <summary>
        /// SortCity
        /// </summary>
    	[DataMember]
    	[DisplayName("SortCity")]
        public virtual string SortCity
        {
            get;
            set;
        }

        #endregion
    }
}
