//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// Sys_ThemeActivity
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_ThemeActivityDtoValidate))]
    public partial class Sys_ThemeActivityDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// 主题ID
        /// </summary>
    	[DataMember]
    	[DisplayName("主题ID")]
        public virtual int ActivityID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 景区ID
        /// </summary>
    	[DataMember]
    	[DisplayName("景区ID")]
        public virtual int ParkID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 主题名
        /// </summary>
    	[DataMember]
    	[DisplayName("主题名")]
        public virtual string Title
        {
            get;
            set;
        }
    
        /// <summary>
        /// 主题编
        /// </summary>
    	[DataMember]
    	[DisplayName("主题编")]
        public virtual string SubTitle
        {
            get;
            set;
        }
    
        /// <summary>
        /// 主题内容
        /// </summary>
    	[DataMember]
    	[DisplayName("主题内容")]
        public virtual string Content
        {
            get;
            set;
        }
    
        /// <summary>
        /// 主题活动URL
        /// </summary>
    	[DataMember]
    	[DisplayName("主题活动URL")]
        public virtual string Url
        {
            get;
            set;
        }
    
        /// <summary>
        /// 景区名
        /// </summary>
    	[DataMember]
    	[DisplayName("景区名")]
        public virtual string ParkTitle
        {
            get;
            set;
        }
    
        /// <summary>
        /// 标签
        /// </summary>
    	[DataMember]
    	[DisplayName("标签")]
        public virtual string Tag
        {
            get;
            set;
        }
    
        /// <summary>
        /// 主题活动时间
        /// </summary>
    	[DataMember]
    	[DisplayName("主题活动时间")]
        public virtual string ActivityTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 添加时间
        /// </summary>
    	[DataMember]
    	[DisplayName("添加时间")]
        public virtual Nullable<System.DateTime> AddTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 是否被删除
        /// </summary>
    	[DataMember]
    	[DisplayName("是否被删除")]
        public virtual Nullable<int> IsDelete
        {
            get;
            set;
        }
    
        /// <summary>
        /// 删除时间
        /// </summary>
    	[DataMember]
    	[DisplayName("删除时间")]
        public virtual Nullable<System.DateTime> DeleteTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 是否顶置
        /// </summary>
    	[DataMember]
    	[DisplayName("是否顶置")]
        public virtual Nullable<int> IsTop
        {
            get;
            set;
        }
    
        /// <summary>
        /// 顶置时间
        /// </summary>
    	[DataMember]
    	[DisplayName("顶置时间")]
        public virtual Nullable<System.DateTime> TopTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 是否推荐
        /// </summary>
    	[DataMember]
    	[DisplayName("是否推荐")]
        public virtual Nullable<int> IsVouch
        {
            get;
            set;
        }
    
        /// <summary>
        /// 推荐时间
        /// </summary>
    	[DataMember]
    	[DisplayName("推荐时间")]
        public virtual Nullable<System.DateTime> VouchTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 发布者ID
        /// </summary>
    	[DataMember]
    	[DisplayName("发布者ID")]
        public virtual Nullable<int> UserID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 没有怎么用
        /// </summary>
    	[DataMember]
    	[DisplayName("没有怎么用")]
        public virtual Nullable<int> ViCount
        {
            get;
            set;
        }
    
        /// <summary>
        /// 发布者
        /// </summary>
    	[DataMember]
    	[DisplayName("发布者")]
        public virtual string Editor
        {
            get;
            set;
        }
    
        /// <summary>
        /// 主题活动分类ID
        /// </summary>
    	[DataMember]
    	[DisplayName("主题活动分类ID")]
        public virtual Nullable<int> ClassID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 活动介绍
        /// </summary>
    	[DataMember]
    	[DisplayName("活动介绍")]
        public virtual string Remark
        {
            get;
            set;
        }
    
        /// <summary>
        /// 活动开始时间
        /// </summary>
    	[DataMember]
    	[DisplayName("活动开始时间")]
        public virtual Nullable<System.DateTime> StartDate
        {
            get;
            set;
        }
    
        /// <summary>
        /// 结束时间
        /// </summary>
    	[DataMember]
    	[DisplayName("结束时间")]
        public virtual Nullable<System.DateTime> EndDate
        {
            get;
            set;
        }
    
        /// <summary>
        /// 主题活动列表图片
        /// </summary>
    	[DataMember]
    	[DisplayName("主题活动列表图片")]
        public virtual string PicUrl
        {
            get;
            set;
        }

        #endregion
    }
}
