//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// Sys_Roles
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_RolesDtoValidate))]
    public partial class Sys_RolesDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// ID
        /// </summary>
    	[DataMember]
    	[DisplayName("ID")]
        public virtual int Id
        {
            get;
            set;
        }
    
        /// <summary>
        /// 角色ID
        /// </summary>
    	[DataMember]
    	[DisplayName("角色ID")]
        public virtual int RoleID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 角色名
        /// </summary>
    	[DataMember]
    	[DisplayName("角色名")]
        public virtual string Description
        {
            get;
            set;
        }

        #endregion
    }
}
