//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// 用户表
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_AdminUserDtoValidate))]
    public partial class Sys_AdminUserDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// 用户Id
        /// </summary>
    	[DataMember]
    	[DisplayName("用户Id")]
        public virtual int id
        {
            get;
            set;
        }
    
        /// <summary>
        /// 用户名
        /// </summary>
    	[DataMember]
    	[DisplayName("用户名")]
        public virtual string username
        {
            get;
            set;
        }
    
        /// <summary>
        /// 密码
        /// </summary>
    	[DataMember]
    	[DisplayName("密码")]
        public virtual string password
        {
            get;
            set;
        }
    
        /// <summary>
        /// 最后一次登陆IP
        /// </summary>
    	[DataMember]
    	[DisplayName("最后一次登陆IP")]
        public virtual string lastloginip
        {
            get;
            set;
        }
    
        /// <summary>
        /// 最后一次登陆时间
        /// </summary>
    	[DataMember]
    	[DisplayName("最后一次登陆时间")]
        public virtual Nullable<System.DateTime> lastlogintime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 登陆次数
        /// </summary>
    	[DataMember]
    	[DisplayName("登陆次数")]
        public virtual Nullable<int> logintimes
        {
            get;
            set;
        }
    
        /// <summary>
        /// 角色Id
        /// </summary>
    	[DataMember]
    	[DisplayName("角色Id")]
        public virtual Nullable<int> roleid
        {
            get;
            set;
        }
    
        /// <summary>
        /// 操作用户Id
        /// </summary>
    	[DataMember]
    	[DisplayName("操作用户Id")]
        public virtual Nullable<int> userid
        {
            get;
            set;
        }
    
        /// <summary>
        /// 真实名
        /// </summary>
    	[DataMember]
    	[DisplayName("真实名")]
        public virtual string truename
        {
            get;
            set;
        }
    
        /// <summary>
        /// 主题样式名
        /// </summary>
    	[DataMember]
    	[DisplayName("主题样式名")]
        public virtual Nullable<int> style
        {
            get;
            set;
        }
    
        /// <summary>
        /// 性别
        /// </summary>
    	[DataMember]
    	[DisplayName("性别")]
        public virtual string sex
        {
            get;
            set;
        }
    
        /// <summary>
        /// 电话
        /// </summary>
    	[DataMember]
    	[DisplayName("电话")]
        public virtual string Phone
        {
            get;
            set;
        }
    
        /// <summary>
        /// 用户类型
        /// </summary>
    	[DataMember]
    	[DisplayName("用户类型")]
        public virtual string UserType
        {
            get;
            set;
        }
    
        /// <summary>
        /// 用户标识
        /// </summary>
    	[DataMember]
    	[DisplayName("用户标识")]
        public virtual string UserGuid
        {
            get;
            set;
        }
    
        /// <summary>
        /// 部门Id
        /// </summary>
    	[DataMember]
    	[DisplayName("部门Id")]
        public virtual string DepartmentID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 邮箱
        /// </summary>
    	[DataMember]
    	[DisplayName("邮箱")]
        public virtual string Email
        {
            get;
            set;
        }
    
        /// <summary>
        /// 是否激活
        /// </summary>
    	[DataMember]
    	[DisplayName("是否激活")]
        public virtual Nullable<bool> Activity
        {
            get;
            set;
        }
    
        /// <summary>
        /// 员工号
        /// </summary>
    	[DataMember]
    	[DisplayName("员工号")]
        public virtual Nullable<int> EmployeeID
        {
            get;
            set;
        }

        #endregion
    }
}
