//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// Sys_VideoComm
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_VideoCommDtoValidate))]
    public partial class Sys_VideoCommDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// 评论ID
        /// </summary>
    	[DataMember]
    	[DisplayName("评论ID")]
        public virtual int CommID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 评论人ID
        /// </summary>
    	[DataMember]
    	[DisplayName("评论人ID")]
        public virtual int UserID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 评论人名
        /// </summary>
    	[DataMember]
    	[DisplayName("评论人名")]
        public virtual string UserName
        {
            get;
            set;
        }
    
        /// <summary>
        /// 评论视频ID
        /// </summary>
    	[DataMember]
    	[DisplayName("评论视频ID")]
        public virtual int VideoID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 评论内容
        /// </summary>
    	[DataMember]
    	[DisplayName("评论内容")]
        public virtual string Content
        {
            get;
            set;
        }
    
        /// <summary>
        /// 评论人IP
        /// </summary>
    	[DataMember]
    	[DisplayName("评论人IP")]
        public virtual string Ip
        {
            get;
            set;
        }
    
        /// <summary>
        /// 地址
        /// </summary>
    	[DataMember]
    	[DisplayName("地址")]
        public virtual System.DateTime AddTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 评分
        /// </summary>
    	[DataMember]
    	[DisplayName("评分")]
        public virtual int Fen
        {
            get;
            set;
        }
    
        /// <summary>
        /// 视频时间
        /// </summary>
    	[DataMember]
    	[DisplayName("视频时间")]
        public virtual string VideoTime
        {
            get;
            set;
        }

        #endregion
    }
}
