//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

using System.ComponentModel;
using System.Runtime.Serialization;
using Miaow.Domain.Dto.Validate;


namespace Miaow.Domain.Dto
{
    ////
    //using System.ComponentModel;
    //////using System.Runtime.Serialization;
    //
    /// <summary>
    /// sys_administrator
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(sys_administratorDtoValidate))]
    public partial class sys_administratorDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// admin_id
        /// </summary>
    	[DataMember]
    	[DisplayName("admin_id")]
        public virtual string admin_id
        {
            get;
            set;
        }
    
        /// <summary>
        /// display_name
        /// </summary>
    	[DataMember]
    	[DisplayName("display_name")]
        public virtual string display_name
        {
            get;
            set;
        }
    
        /// <summary>
        /// password
        /// </summary>
    	[DataMember]
    	[DisplayName("password")]
        public virtual string password
        {
            get;
            set;
        }
    
        /// <summary>
        /// old_pasword
        /// </summary>
    	[DataMember]
    	[DisplayName("old_pasword")]
        public virtual string old_pasword
        {
            get;
            set;
        }
    
        /// <summary>
        /// email
        /// </summary>
    	[DataMember]
    	[DisplayName("email")]
        public virtual string email
        {
            get;
            set;
        }
    
        /// <summary>
        /// enabled
        /// </summary>
    	[DataMember]
    	[DisplayName("enabled")]
        public virtual int enabled
        {
            get;
            set;
        }
    
        /// <summary>
        /// created_time
        /// </summary>
    	[DataMember]
    	[DisplayName("created_time")]
        public virtual System.DateTime created_time
        {
            get;
            set;
        }
    
        /// <summary>
        /// updated_time
        /// </summary>
    	[DataMember]
    	[DisplayName("updated_time")]
        public virtual Nullable<System.DateTime> updated_time
        {
            get;
            set;
        }
    
        /// <summary>
        /// deleted
        /// </summary>
    	[DataMember]
    	[DisplayName("deleted")]
        public virtual Nullable<int> deleted
        {
            get;
            set;
        }

        #endregion

    }
}
