//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// Sys_HotelPropertyInfo2
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_HotelPropertyInfo2DtoValidate))]
    public partial class Sys_HotelPropertyInfo2Dto
    {
        #region Primitive Properties
    
        /// <summary>
        /// ID
        /// </summary>
    	[DataMember]
    	[DisplayName("ID")]
        public virtual int ID
        {
            get;
            set;
        }
    
        /// <summary>
        /// HotelID
        /// </summary>
    	[DataMember]
    	[DisplayName("HotelID")]
        public virtual Nullable<int> HotelID
        {
            get;
            set;
        }
    
        /// <summary>
        /// HotelName
        /// </summary>
    	[DataMember]
    	[DisplayName("HotelName")]
        public virtual string HotelName
        {
            get;
            set;
        }
    
        /// <summary>
        /// City
        /// </summary>
    	[DataMember]
    	[DisplayName("City")]
        public virtual string City
        {
            get;
            set;
        }
    
        /// <summary>
        /// Address
        /// </summary>
    	[DataMember]
    	[DisplayName("Address")]
        public virtual string Address
        {
            get;
            set;
        }
    
        /// <summary>
        /// ContactName
        /// </summary>
    	[DataMember]
    	[DisplayName("ContactName")]
        public virtual string ContactName
        {
            get;
            set;
        }
    
        /// <summary>
        /// latitude
        /// </summary>
    	[DataMember]
    	[DisplayName("latitude")]
        public virtual string latitude
        {
            get;
            set;
        }
    
        /// <summary>
        /// longitude
        /// </summary>
    	[DataMember]
    	[DisplayName("longitude")]
        public virtual string longitude
        {
            get;
            set;
        }
    
        /// <summary>
        /// Starrating
        /// </summary>
    	[DataMember]
    	[DisplayName("Starrating")]
        public virtual string Starrating
        {
            get;
            set;
        }
    
        /// <summary>
        /// Fax
        /// </summary>
    	[DataMember]
    	[DisplayName("Fax")]
        public virtual string Fax
        {
            get;
            set;
        }
    
        /// <summary>
        /// Transportation
        /// </summary>
    	[DataMember]
    	[DisplayName("Transportation")]
        public virtual string Transportation
        {
            get;
            set;
        }
    
        /// <summary>
        /// Property
        /// </summary>
    	[DataMember]
    	[DisplayName("Property")]
        public virtual string Property
        {
            get;
            set;
        }
    
        /// <summary>
        /// Attractions
        /// </summary>
    	[DataMember]
    	[DisplayName("Attractions")]
        public virtual string Attractions
        {
            get;
            set;
        }
    
        /// <summary>
        /// Dateopened
        /// </summary>
    	[DataMember]
    	[DisplayName("Dateopened")]
        public virtual string Dateopened
        {
            get;
            set;
        }
    
        /// <summary>
        /// Recreation
        /// </summary>
    	[DataMember]
    	[DisplayName("Recreation")]
        public virtual string Recreation
        {
            get;
            set;
        }
    
        /// <summary>
        /// Dining
        /// </summary>
    	[DataMember]
    	[DisplayName("Dining")]
        public virtual string Dining
        {
            get;
            set;
        }
    
        /// <summary>
        /// Meetings
        /// </summary>
    	[DataMember]
    	[DisplayName("Meetings")]
        public virtual string Meetings
        {
            get;
            set;
        }
    
        /// <summary>
        /// Phone
        /// </summary>
    	[DataMember]
    	[DisplayName("Phone")]
        public virtual string Phone
        {
            get;
            set;
        }
    
        /// <summary>
        /// LiveInCount
        /// </summary>
    	[DataMember]
    	[DisplayName("LiveInCount")]
        public virtual Nullable<int> LiveInCount
        {
            get;
            set;
        }
    
        /// <summary>
        /// CommCount
        /// </summary>
    	[DataMember]
    	[DisplayName("CommCount")]
        public virtual Nullable<int> CommCount
        {
            get;
            set;
        }
    
        /// <summary>
        /// Score
        /// </summary>
    	[DataMember]
    	[DisplayName("Score")]
        public virtual Nullable<int> Score
        {
            get;
            set;
        }
    
        /// <summary>
        /// VisitCount
        /// </summary>
    	[DataMember]
    	[DisplayName("VisitCount")]
        public virtual Nullable<int> VisitCount
        {
            get;
            set;
        }
    
        /// <summary>
        /// CirHotelID
        /// </summary>
    	[DataMember]
    	[DisplayName("CirHotelID")]
        public virtual string CirHotelID
        {
            get;
            set;
        }
    
        /// <summary>
        /// Facilities
        /// </summary>
    	[DataMember]
    	[DisplayName("Facilities")]
        public virtual string Facilities
        {
            get;
            set;
        }
    
        /// <summary>
        /// MinPrice
        /// </summary>
    	[DataMember]
    	[DisplayName("MinPrice")]
        public virtual string MinPrice
        {
            get;
            set;
        }
    
        /// <summary>
        /// MaxPrice
        /// </summary>
    	[DataMember]
    	[DisplayName("MaxPrice")]
        public virtual string MaxPrice
        {
            get;
            set;
        }
    
        /// <summary>
        /// Location
        /// </summary>
    	[DataMember]
    	[DisplayName("Location")]
        public virtual string Location
        {
            get;
            set;
        }
    
        /// <summary>
        /// ResideTime
        /// </summary>
    	[DataMember]
    	[DisplayName("ResideTime")]
        public virtual string ResideTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// LateResideTime
        /// </summary>
    	[DataMember]
    	[DisplayName("LateResideTime")]
        public virtual string LateResideTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// bookurl
        /// </summary>
    	[DataMember]
    	[DisplayName("bookurl")]
        public virtual string bookurl
        {
            get;
            set;
        }
    
        /// <summary>
        /// MapUrl
        /// </summary>
    	[DataMember]
    	[DisplayName("MapUrl")]
        public virtual string MapUrl
        {
            get;
            set;
        }
    
        /// <summary>
        /// HotelClass
        /// </summary>
    	[DataMember]
    	[DisplayName("HotelClass")]
        public virtual string HotelClass
        {
            get;
            set;
        }
    
        /// <summary>
        /// photo
        /// </summary>
    	[DataMember]
    	[DisplayName("photo")]
        public virtual string photo
        {
            get;
            set;
        }
    
        /// <summary>
        /// Source
        /// </summary>
    	[DataMember]
    	[DisplayName("Source")]
        public virtual string Source
        {
            get;
            set;
        }
    
        /// <summary>
        /// Area
        /// </summary>
    	[DataMember]
    	[DisplayName("Area")]
        public virtual string Area
        {
            get;
            set;
        }
    
        /// <summary>
        /// Accuracy
        /// </summary>
    	[DataMember]
    	[DisplayName("Accuracy")]
        public virtual Nullable<int> Accuracy
        {
            get;
            set;
        }
    
        /// <summary>
        /// HaveCoordinate
        /// </summary>
    	[DataMember]
    	[DisplayName("HaveCoordinate")]
        public virtual Nullable<bool> HaveCoordinate
        {
            get;
            set;
        }
    
        /// <summary>
        /// Province
        /// </summary>
    	[DataMember]
    	[DisplayName("Province")]
        public virtual string Province
        {
            get;
            set;
        }
    
        /// <summary>
        /// ProvincePY
        /// </summary>
    	[DataMember]
    	[DisplayName("ProvincePY")]
        public virtual string ProvincePY
        {
            get;
            set;
        }
    
        /// <summary>
        /// CirSightID
        /// </summary>
    	[DataMember]
    	[DisplayName("CirSightID")]
        public virtual string CirSightID
        {
            get;
            set;
        }
    
        /// <summary>
        /// PicCount
        /// </summary>
    	[DataMember]
    	[DisplayName("PicCount")]
        public virtual Nullable<int> PicCount
        {
            get;
            set;
        }
    
        /// <summary>
        /// AreaCode
        /// </summary>
    	[DataMember]
    	[DisplayName("AreaCode")]
        public virtual string AreaCode
        {
            get;
            set;
        }

        #endregion
    }
}
