//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// Sys_VouchInfo
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_VouchInfoDtoValidate))]
    public partial class Sys_VouchInfoDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// 推荐ID
        /// </summary>
    	[DataMember]
    	[DisplayName("推荐ID")]
        public virtual int VouchID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 推荐类型（春，夏，秋，冬）
        /// </summary>
    	[DataMember]
    	[DisplayName("推荐类型（春，夏，秋，冬）")]
        public virtual string DataType
        {
            get;
            set;
        }
    
        /// <summary>
        /// 城市
        /// </summary>
    	[DataMember]
    	[DisplayName("城市")]
        public virtual string CityS
        {
            get;
            set;
        }

        #endregion
    }
}
