//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// 文章评论表
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_ArticleCommDtoValidate))]
    public partial class Sys_ArticleCommDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// 评论ID
        /// </summary>
    	[DataMember]
    	[DisplayName("评论ID")]
        public virtual int CommID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 添加用户Id
        /// </summary>
    	[DataMember]
    	[DisplayName("添加用户Id")]
        public virtual int UserID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 添加用户名
        /// </summary>
    	[DataMember]
    	[DisplayName("添加用户名")]
        public virtual string UserName
        {
            get;
            set;
        }
    
        /// <summary>
        /// 文章Id
        /// </summary>
    	[DataMember]
    	[DisplayName("文章Id")]
        public virtual int ArticleID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 评论内容
        /// </summary>
    	[DataMember]
    	[DisplayName("评论内容")]
        public virtual string Content
        {
            get;
            set;
        }
    
        /// <summary>
        /// 评论Ip
        /// </summary>
    	[DataMember]
    	[DisplayName("评论Ip")]
        public virtual string Ip
        {
            get;
            set;
        }
    
        /// <summary>
        /// 添加时间
        /// </summary>
    	[DataMember]
    	[DisplayName("添加时间")]
        public virtual System.DateTime AddTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 评论给分
        /// </summary>
    	[DataMember]
    	[DisplayName("评论给分")]
        public virtual int Fen
        {
            get;
            set;
        }

        #endregion
    }
}
