//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// Sys_SightVouch
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_SightVouchDtoValidate))]
    public partial class Sys_SightVouchDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// 推荐表ID
        /// </summary>
    	[DataMember]
    	[DisplayName("推荐表ID")]
        public virtual int VouchID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 数据类型 /推荐名
        /// </summary>
    	[DataMember]
    	[DisplayName("数据类型 /推荐名")]
        public virtual string ClassName
        {
            get;
            set;
        }
    
        /// <summary>
        /// 景区ID
        /// </summary>
    	[DataMember]
    	[DisplayName("景区ID")]
        public virtual string SightIds
        {
            get;
            set;
        }
    
        /// <summary>
        /// 推荐城市
        /// </summary>
    	[DataMember]
    	[DisplayName("推荐城市")]
        public virtual string City
        {
            get;
            set;
        }
    
        /// <summary>
        /// 添加时间
        /// </summary>
    	[DataMember]
    	[DisplayName("添加时间")]
        public virtual Nullable<System.DateTime> AddTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 周边城市
        /// </summary>
    	[DataMember]
    	[DisplayName("周边城市")]
        public virtual string CirCity
        {
            get;
            set;
        }
    
        /// <summary>
        /// 推荐城市拼音
        /// </summary>
    	[DataMember]
    	[DisplayName("推荐城市拼音")]
        public virtual string CityPy
        {
            get;
            set;
        }
    
        /// <summary>
        /// 景区名
        /// </summary>
    	[DataMember]
    	[DisplayName("景区名")]
        public virtual string SightNames
        {
            get;
            set;
        }
    
        /// <summary>
        /// 推荐省
        /// </summary>
    	[DataMember]
    	[DisplayName("推荐省")]
        public virtual string Province
        {
            get;
            set;
        }

        #endregion
    }
}
