//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

using System.ComponentModel;
using System.Runtime.Serialization;
using Miaow.Domain.Dto.Validate;


namespace Miaow.Domain.Dto
{
    ////
    //using System.ComponentModel;
    //////using System.Runtime.Serialization;
    //
    /// <summary>
    /// sys_roles
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(sys_rolesDtoValidate))]
    public partial class sys_rolesDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// role_id
        /// </summary>
    	[DataMember]
    	[DisplayName("role_id")]
        public virtual string role_id
        {
            get;
            set;
        }
    
        /// <summary>
        /// role_name
        /// </summary>
    	[DataMember]
    	[DisplayName("role_name")]
        public virtual string role_name
        {
            get;
            set;
        }
    
        /// <summary>
        /// system_id
        /// </summary>
    	[DataMember]
    	[DisplayName("system_id")]
        public virtual string system_id
        {
            get;
            set;
        }
    
        /// <summary>
        /// created_time
        /// </summary>
    	[DataMember]
    	[DisplayName("created_time")]
        public virtual System.DateTime created_time
        {
            get;
            set;
        }
    
        /// <summary>
        /// updated_time
        /// </summary>
    	[DataMember]
    	[DisplayName("updated_time")]
        public virtual System.DateTime updated_time
        {
            get;
            set;
        }
    
        /// <summary>
        /// remark
        /// </summary>
    	[DataMember]
    	[DisplayName("remark")]
        public virtual string remark
        {
            get;
            set;
        }
    
        /// <summary>
        /// deleted
        /// </summary>
    	[DataMember]
    	[DisplayName("deleted")]
        public virtual int deleted
        {
            get;
            set;
        }
    
        /// <summary>
        /// admin_id
        /// </summary>
    	[DataMember]
    	[DisplayName("admin_id")]
        public virtual string admin_id
        {
            get;
            set;
        }

        #endregion

    }
}
