//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// Sys_SightComm
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_SightCommDtoValidate))]
    public partial class Sys_SightCommDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// 评论ID
        /// </summary>
    	[DataMember]
    	[DisplayName("评论ID")]
        public virtual int CommID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 用户ID
        /// </summary>
    	[DataMember]
    	[DisplayName("用户ID")]
        public virtual int UserID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 用户名
        /// </summary>
    	[DataMember]
    	[DisplayName("用户名")]
        public virtual string UserName
        {
            get;
            set;
        }
    
        /// <summary>
        /// 景区ID
        /// </summary>
    	[DataMember]
    	[DisplayName("景区ID")]
        public virtual int SightID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 内容
        /// </summary>
    	[DataMember]
    	[DisplayName("内容")]
        public virtual string Content
        {
            get;
            set;
        }
    
        /// <summary>
        /// IP地址
        /// </summary>
    	[DataMember]
    	[DisplayName("IP地址")]
        public virtual string Ip
        {
            get;
            set;
        }
    
        /// <summary>
        /// 添加时间
        /// </summary>
    	[DataMember]
    	[DisplayName("添加时间")]
        public virtual System.DateTime AddTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 评分
        /// </summary>
    	[DataMember]
    	[DisplayName("评分")]
        public virtual int Fen
        {
            get;
            set;
        }
    
        /// <summary>
        /// 父节点
        /// </summary>
    	[DataMember]
    	[DisplayName("父节点")]
        public virtual int ParentID
        {
            get;
            set;
        }

        #endregion
    }
}
