//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// Sys_PicClass
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_PicClassDtoValidate))]
    public partial class Sys_PicClassDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// 图片分类ID
        /// </summary>
    	[DataMember]
    	[DisplayName("图片分类ID")]
        public virtual int ClassID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 图片分类名称
        /// </summary>
    	[DataMember]
    	[DisplayName("图片分类名称")]
        public virtual string ClassName
        {
            get;
            set;
        }
    
        /// <summary>
        /// 父ID
        /// </summary>
    	[DataMember]
    	[DisplayName("父ID")]
        public virtual int ParentID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 分类路径
        /// </summary>
    	[DataMember]
    	[DisplayName("分类路径")]
        public virtual string ClassPath
        {
            get;
            set;
        }
    
        /// <summary>
        /// 分类深度
        /// </summary>
    	[DataMember]
    	[DisplayName("分类深度")]
        public virtual int ClassDepth
        {
            get;
            set;
        }
    
        /// <summary>
        /// 分类排序
        /// </summary>
    	[DataMember]
    	[DisplayName("分类排序")]
        public virtual int ClassOrder
        {
            get;
            set;
        }
    
        /// <summary>
        /// 分类简介
        /// </summary>
    	[DataMember]
    	[DisplayName("分类简介")]
        public virtual string ClassIntro
        {
            get;
            set;
        }
    
        /// <summary>
        /// 是否删除
        /// </summary>
    	[DataMember]
    	[DisplayName("是否删除")]
        public virtual int IsDelete
        {
            get;
            set;
        }
    
        /// <summary>
        /// 模板ID
        /// </summary>
    	[DataMember]
    	[DisplayName("模板ID")]
        public virtual Nullable<int> DemoID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 删除时间
        /// </summary>
    	[DataMember]
    	[DisplayName("删除时间")]
        public virtual Nullable<System.DateTime> DeleteTime
        {
            get;
            set;
        }

        #endregion
    }
}
