//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

using System.ComponentModel;
using System.Runtime.Serialization;
using Miaow.Domain.Dto.Validate;


namespace Miaow.Domain.Dto
{
    ////
    //using System.ComponentModel;
    //////using System.Runtime.Serialization;
    //
    /// <summary>
    /// sys_controller_action
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(sys_controller_actionDtoValidate))]
    public partial class sys_controller_actionDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// controller_action_id
        /// </summary>
    	[DataMember]
    	[DisplayName("controller_action_id")]
        public virtual string controller_action_id
        {
            get;
            set;
        }
    
        /// <summary>
        /// controller_id
        /// </summary>
    	[DataMember]
    	[DisplayName("controller_id")]
        public virtual System.Guid controller_id
        {
            get;
            set;
        }
    
        /// <summary>
        /// action_id
        /// </summary>
    	[DataMember]
    	[DisplayName("action_id")]
        public virtual string action_id
        {
            get;
            set;
        }
    
        /// <summary>
        /// created_time
        /// </summary>
    	[DataMember]
    	[DisplayName("created_time")]
        public virtual System.DateTime created_time
        {
            get;
            set;
        }
    
        /// <summary>
        /// updated_time
        /// </summary>
    	[DataMember]
    	[DisplayName("updated_time")]
        public virtual Nullable<System.DateTime> updated_time
        {
            get;
            set;
        }
    
        /// <summary>
        /// remark
        /// </summary>
    	[DataMember]
    	[DisplayName("remark")]
        public virtual string remark
        {
            get;
            set;
        }
    
        /// <summary>
        /// admin_Id
        /// </summary>
    	[DataMember]
    	[DisplayName("admin_Id")]
        public virtual string admin_Id
        {
            get;
            set;
        }
    
        /// <summary>
        /// deleted
        /// </summary>
    	[DataMember]
    	[DisplayName("deleted")]
        public virtual int deleted
        {
            get;
            set;
        }

        #endregion

    }
}
