//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// 酒店图片表
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_HotelPicDtoValidate))]
    public partial class Sys_HotelPicDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// 图片Id
        /// </summary>
    	[DataMember]
    	[DisplayName("图片Id")]
        public virtual int PicID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 酒店Id
        /// </summary>
    	[DataMember]
    	[DisplayName("酒店Id")]
        public virtual int HotelID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 图片路径(没有FileNam)
        /// </summary>
    	[DataMember]
    	[DisplayName("图片路径")]
        public virtual string PicPath
        {
            get;
            set;
        }
    
        /// <summary>
        /// 图片名
        /// </summary>
    	[DataMember]
    	[DisplayName("图片名")]
        public virtual string PicName
        {
            get;
            set;
        }
    
        /// <summary>
        /// 是否是大图
        /// </summary>
    	[DataMember]
    	[DisplayName("是否是大图")]
        public virtual Nullable<int> IsLarge
        {
            get;
            set;
        }
    
        /// <summary>
        /// 来源
        /// </summary>
    	[DataMember]
    	[DisplayName("来源")]
        public virtual string Source
        {
            get;
            set;
        }

        #endregion
    }
}
