//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// Sys_SightInfoSort
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_SightInfoSortDtoValidate))]
    public partial class Sys_SightInfoSortDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// 自增ID
        /// </summary>
    	[DataMember]
    	[DisplayName("自增ID")]
        public virtual int Id
        {
            get;
            set;
        }
    
        /// <summary>
        /// 景区ID
        /// </summary>
    	[DataMember]
    	[DisplayName("景区ID")]
        public virtual Nullable<int> SightId
        {
            get;
            set;
        }
    
        /// <summary>
        /// 强制排序类型（1为市，2为省，3为全局，其他无效）
        /// </summary>
    	[DataMember]
    	[DisplayName("强制排序类型（1为市，2为省，3为全局，其他无效）")]
        public virtual Nullable<int> Type
        {
            get;
            set;
        }
    
        /// <summary>
        /// 市，省，ALL
        /// </summary>
    	[DataMember]
    	[DisplayName("市，省，ALL")]
        public virtual string Target
        {
            get;
            set;
        }
    
        /// <summary>
        /// 排序位置
        /// </summary>
    	[DataMember]
    	[DisplayName("排序位置")]
        public virtual Nullable<int> SortNum
        {
            get;
            set;
        }
    
        /// <summary>
        /// 操作用户Id
        /// </summary>
    	[DataMember]
    	[DisplayName("操作用户Id")]
        public virtual Nullable<int> UserId
        {
            get;
            set;
        }
    
        /// <summary>
        /// 添加时间
        /// </summary>
    	[DataMember]
    	[DisplayName("添加时间")]
        public virtual Nullable<System.DateTime> AddTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 状态
        /// </summary>
    	[DataMember]
    	[DisplayName("状态 ")]
        public virtual Nullable<bool> State
        {
            get;
            set;
        }

        #endregion
    }
}
