//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// Sys_UserAction
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_UserActionDtoValidate))]
    public partial class Sys_UserActionDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// 用户行为ID
        /// </summary>
    	[DataMember]
    	[DisplayName("用户行为ID")]
        public virtual int ActionID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 操作名称
        /// </summary>
    	[DataMember]
    	[DisplayName("操作名称")]
        public virtual string ChannelName
        {
            get;
            set;
        }

        #endregion
    }
}
