//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// sys_phone_ly
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.sys_phone_lyDtoValidate))]
    public partial class sys_phone_lyDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// 评论ID
        /// </summary>
    	[DataMember]
    	[DisplayName("评论ID")]
        public virtual int Mid
        {
            get;
            set;
        }
    
        /// <summary>
        /// 用户名
        /// </summary>
    	[DataMember]
    	[DisplayName("用户名")]
        public virtual string username
        {
            get;
            set;
        }
    
        /// <summary>
        /// 标题
        /// </summary>
    	[DataMember]
    	[DisplayName("标题")]
        public virtual string title
        {
            get;
            set;
        }
    
        /// <summary>
        /// 内容
        /// </summary>
    	[DataMember]
    	[DisplayName("内容")]
        public virtual string content
        {
            get;
            set;
        }
    
        /// <summary>
        /// 添加时间
        /// </summary>
    	[DataMember]
    	[DisplayName("添加时间")]
        public virtual Nullable<System.DateTime> addtime
        {
            get;
            set;
        }
    
        /// <summary>
        /// IP地址
        /// </summary>
    	[DataMember]
    	[DisplayName("IP地址")]
        public virtual string ip
        {
            get;
            set;
        }

        #endregion
    }
}
