//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// 模板分类表
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_DemoClassDtoValidate))]
    public partial class Sys_DemoClassDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// 模板分类ID
        /// </summary>
    	[DataMember]
    	[DisplayName("模板分类ID")]
        public virtual int ClassID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 模板名
        /// </summary>
    	[DataMember]
    	[DisplayName("模板名")]
        public virtual string ClassName
        {
            get;
            set;
        }
    
        /// <summary>
        /// 所属父ID
        /// </summary>
    	[DataMember]
    	[DisplayName("所属父ID")]
        public virtual int ParentID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 分类字符串
        /// </summary>
    	[DataMember]
    	[DisplayName("分类字符串")]
        public virtual string ClassPath
        {
            get;
            set;
        }
    
        /// <summary>
        /// 分类深度
        /// </summary>
    	[DataMember]
    	[DisplayName("分类深度")]
        public virtual int ClassDepth
        {
            get;
            set;
        }
    
        /// <summary>
        /// 排序号
        /// </summary>
    	[DataMember]
    	[DisplayName("排序号")]
        public virtual int ClassOrder
        {
            get;
            set;
        }
    
        /// <summary>
        /// 说明
        /// </summary>
    	[DataMember]
    	[DisplayName("说明")]
        public virtual string ClassIntro
        {
            get;
            set;
        }
    
        /// <summary>
        /// 是否被删除
        /// </summary>
    	[DataMember]
    	[DisplayName("是否被删除")]
        public virtual int IsDelete
        {
            get;
            set;
        }
    
        /// <summary>
        /// 删除时间
        /// </summary>
    	[DataMember]
    	[DisplayName("删除时间")]
        public virtual Nullable<System.DateTime> DeleteTime
        {
            get;
            set;
        }

        #endregion
    }
}
