//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// Sys_PicInfo
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_PicInfoDtoValidate))]
    public partial class Sys_PicInfoDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// 图片ID
        /// </summary>
    	[DataMember]
    	[DisplayName("图片ID")]
        public virtual int PicID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 图片名
        /// </summary>
    	[DataMember]
    	[DisplayName("图片名")]
        public virtual string PicName
        {
            get;
            set;
        }
    
        /// <summary>
        /// 图片分类ID
        /// </summary>
    	[DataMember]
    	[DisplayName("图片分类ID")]
        public virtual Nullable<int> ClassID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 说明
        /// </summary>
    	[DataMember]
    	[DisplayName("说明")]
        public virtual string Remark
        {
            get;
            set;
        }
    
        /// <summary>
        /// 点击数
        /// </summary>
    	[DataMember]
    	[DisplayName("点击数")]
        public virtual Nullable<int> ViewCount
        {
            get;
            set;
        }
    
        /// <summary>
        /// 图片路径
        /// </summary>
    	[DataMember]
    	[DisplayName("图片路径")]
        public virtual string PicPath
        {
            get;
            set;
        }
    
        /// <summary>
        /// 文件名
        /// </summary>
    	[DataMember]
    	[DisplayName("文件名")]
        public virtual string FileName
        {
            get;
            set;
        }
    
        /// <summary>
        /// 景区ID
        /// </summary>
    	[DataMember]
    	[DisplayName("景区ID")]
        public virtual Nullable<int> ParkID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 图片标签
        /// </summary>
    	[DataMember]
    	[DisplayName("图片标签")]
        public virtual string Tag
        {
            get;
            set;
        }
    
        /// <summary>
        /// 用户ID
        /// </summary>
    	[DataMember]
    	[DisplayName("用户ID")]
        public virtual Nullable<int> UserID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 来源
        /// </summary>
    	[DataMember]
    	[DisplayName("来源")]
        public virtual string InSource
        {
            get;
            set;
        }
    
        /// <summary>
        /// 添加时间
        /// </summary>
    	[DataMember]
    	[DisplayName("添加时间")]
        public virtual Nullable<System.DateTime> AddTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// IsAud
        /// </summary>
    	[DataMember]
    	[DisplayName("IsAud")]
        public virtual Nullable<int> IsAud
        {
            get;
            set;
        }
    
        /// <summary>
        /// AudTime
        /// </summary>
    	[DataMember]
    	[DisplayName("AudTime")]
        public virtual Nullable<System.DateTime> AudTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// Auditor
        /// </summary>
    	[DataMember]
    	[DisplayName("Auditor")]
        public virtual Nullable<int> Auditor
        {
            get;
            set;
        }
    
        /// <summary>
        /// 是否推荐
        /// </summary>
    	[DataMember]
    	[DisplayName("是否推荐")]
        public virtual Nullable<int> IsVouch
        {
            get;
            set;
        }
    
        /// <summary>
        /// 推荐时间
        /// </summary>
    	[DataMember]
    	[DisplayName("推荐时间")]
        public virtual Nullable<System.DateTime> VouchTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 是否删除
        /// </summary>
    	[DataMember]
    	[DisplayName("是否删除")]
        public virtual Nullable<int> IsDelete
        {
            get;
            set;
        }
    
        /// <summary>
        /// 删除时间
        /// </summary>
    	[DataMember]
    	[DisplayName("删除时间")]
        public virtual Nullable<System.DateTime> DeTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 评论数
        /// </summary>
    	[DataMember]
    	[DisplayName("评论数")]
        public virtual Nullable<int> CommCount
        {
            get;
            set;
        }
    
        /// <summary>
        /// 最后访问时间
        /// </summary>
    	[DataMember]
    	[DisplayName("最后访问时间")]
        public virtual Nullable<System.DateTime> VisitTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 今日访问量
        /// </summary>
    	[DataMember]
    	[DisplayName("今日访问量")]
        public virtual Nullable<int> TodayCount
        {
            get;
            set;
        }
    
        /// <summary>
        /// IsArticle
        /// </summary>
    	[DataMember]
    	[DisplayName("IsArticle")]
        public virtual Nullable<int> IsArticle
        {
            get;
            set;
        }

        #endregion
    }
}
