//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// Sys_HotelDailyRates2
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_HotelDailyRates2DtoValidate))]
    public partial class Sys_HotelDailyRates2Dto
    {
        #region Primitive Properties
    
        /// <summary>
        /// DailyRatesID
        /// </summary>
    	[DataMember]
    	[DisplayName("DailyRatesID")]
        public virtual int DailyRatesID
        {
            get;
            set;
        }
    
        /// <summary>
        /// HotelID
        /// </summary>
    	[DataMember]
    	[DisplayName("HotelID")]
        public virtual Nullable<int> HotelID
        {
            get;
            set;
        }
    
        /// <summary>
        /// RoomType
        /// </summary>
    	[DataMember]
    	[DisplayName("RoomType")]
        public virtual string RoomType
        {
            get;
            set;
        }
    
        /// <summary>
        /// RoomName
        /// </summary>
    	[DataMember]
    	[DisplayName("RoomName")]
        public virtual string RoomName
        {
            get;
            set;
        }
    
        /// <summary>
        /// RoomDescription
        /// </summary>
    	[DataMember]
    	[DisplayName("RoomDescription")]
        public virtual string RoomDescription
        {
            get;
            set;
        }
    
        /// <summary>
        /// Allotment
        /// </summary>
    	[DataMember]
    	[DisplayName("Allotment")]
        public virtual Nullable<int> Allotment
        {
            get;
            set;
        }
    
        /// <summary>
        /// LeadTime
        /// </summary>
    	[DataMember]
    	[DisplayName("LeadTime")]
        public virtual Nullable<int> LeadTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// MinLos
        /// </summary>
    	[DataMember]
    	[DisplayName("MinLos")]
        public virtual Nullable<int> MinLos
        {
            get;
            set;
        }
    
        /// <summary>
        /// MaxLos
        /// </summary>
    	[DataMember]
    	[DisplayName("MaxLos")]
        public virtual Nullable<int> MaxLos
        {
            get;
            set;
        }
    
        /// <summary>
        /// DoubleRates
        /// </summary>
    	[DataMember]
    	[DisplayName("DoubleRates")]
        public virtual string DoubleRates
        {
            get;
            set;
        }
    
        /// <summary>
        /// GUA
        /// </summary>
    	[DataMember]
    	[DisplayName("GUA")]
        public virtual string GUA
        {
            get;
            set;
        }
    
        /// <summary>
        /// CXL
        /// </summary>
    	[DataMember]
    	[DisplayName("CXL")]
        public virtual string CXL
        {
            get;
            set;
        }
    
        /// <summary>
        /// RateCode
        /// </summary>
    	[DataMember]
    	[DisplayName("RateCode")]
        public virtual string RateCode
        {
            get;
            set;
        }
    
        /// <summary>
        /// MaxOccupancy
        /// </summary>
    	[DataMember]
    	[DisplayName("MaxOccupancy")]
        public virtual Nullable<int> MaxOccupancy
        {
            get;
            set;
        }
    
        /// <summary>
        /// Source
        /// </summary>
    	[DataMember]
    	[DisplayName("Source")]
        public virtual string Source
        {
            get;
            set;
        }
    
        /// <summary>
        /// RoomAmountAdvice
        /// </summary>
    	[DataMember]
    	[DisplayName("RoomAmountAdvice")]
        public virtual string RoomAmountAdvice
        {
            get;
            set;
        }

        #endregion
    }
}
