//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// Sys_TourPlanDetail
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_TourPlanDetailDtoValidate))]
    public partial class Sys_TourPlanDetailDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// 详细计划ID
        /// </summary>
    	[DataMember]
    	[DisplayName("详细计划ID")]
        public virtual int PlanDetailID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 景区ID或酒店ID
        /// </summary>
    	[DataMember]
    	[DisplayName("景区ID或酒店ID")]
        public virtual Nullable<int> SightIDOrHotelID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 此天价格
        /// </summary>
    	[DataMember]
    	[DisplayName("此天价格")]
        public virtual Nullable<int> CurrentPrice
        {
            get;
            set;
        }
    
        /// <summary>
        /// 说明
        /// </summary>
    	[DataMember]
    	[DisplayName("说明")]
        public virtual string Remark
        {
            get;
            set;
        }
    
        /// <summary>
        /// 没怎么用
        /// </summary>
    	[DataMember]
    	[DisplayName("没怎么用")]
        public virtual Nullable<int> VisitCount
        {
            get;
            set;
        }
    
        /// <summary>
        /// 天数
        /// </summary>
    	[DataMember]
    	[DisplayName("天数")]
        public virtual Nullable<int> DayID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 添加时间
        /// </summary>
    	[DataMember]
    	[DisplayName("添加时间")]
        public virtual Nullable<System.DateTime> AddTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 是否删除
        /// </summary>
    	[DataMember]
    	[DisplayName("是否删除")]
        public virtual Nullable<int> IsDelete
        {
            get;
            set;
        }
    
        /// <summary>
        /// 类型（景区，酒店）
        /// </summary>
    	[DataMember]
    	[DisplayName("类型（景区，酒店）")]
        public virtual string DetailType
        {
            get;
            set;
        }
    
        /// <summary>
        /// 旅游线路ID
        /// </summary>
    	[DataMember]
    	[DisplayName("旅游线路ID")]
        public virtual Nullable<int> PlanID
        {
            get;
            set;
        }

        #endregion
    }
}
