//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// Ip地址表
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_IpAddressDtoValidate))]
    public partial class Sys_IpAddressDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// Id号
        /// </summary>
    	[DataMember]
    	[DisplayName("Id号")]
        public virtual int id
        {
            get;
            set;
        }
    
        /// <summary>
        /// IP1
        /// </summary>
    	[DataMember]
    	[DisplayName("IP1")]
        public virtual Nullable<double> IP1
        {
            get;
            set;
        }
    
        /// <summary>
        /// IP2
        /// </summary>
    	[DataMember]
    	[DisplayName("IP2")]
        public virtual Nullable<double> IP2
        {
            get;
            set;
        }
    
        /// <summary>
        /// 省名
        /// </summary>
    	[DataMember]
    	[DisplayName("省名")]
        public virtual string Province
        {
            get;
            set;
        }
    
        /// <summary>
        /// 市名
        /// </summary>
    	[DataMember]
    	[DisplayName("市名")]
        public virtual string City
        {
            get;
            set;
        }

        #endregion
    }
}
