//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// TripIndexInfo
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.TripIndexInfoDtoValidate))]
    public partial class TripIndexInfoDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// 旅行ID
        /// </summary>
    	[DataMember]
    	[DisplayName("旅行ID")]
        public virtual int id
        {
            get;
            set;
        }
    
        /// <summary>
        /// 旅行名
        /// </summary>
    	[DataMember]
    	[DisplayName("旅行名")]
        public virtual string TripTitle
        {
            get;
            set;
        }
    
        /// <summary>
        /// 景区名
        /// </summary>
    	[DataMember]
    	[DisplayName("景区名")]
        public virtual string Sights
        {
            get;
            set;
        }
    
        /// <summary>
        /// 旅行天数
        /// </summary>
    	[DataMember]
    	[DisplayName("旅行天数")]
        public virtual Nullable<int> Days
        {
            get;
            set;
        }
    
        /// <summary>
        /// 景区地点
        /// </summary>
    	[DataMember]
    	[DisplayName("景区地点")]
        public virtual string Address
        {
            get;
            set;
        }
    
        /// <summary>
        /// 价格
        /// </summary>
    	[DataMember]
    	[DisplayName("价格")]
        public virtual Nullable<double> Price
        {
            get;
            set;
        }
    
        /// <summary>
        /// 酒店中文名（可多个，也可没有）
        /// </summary>
    	[DataMember]
    	[DisplayName("酒店中文名（可多个，也可没有）")]
        public virtual string Hotels
        {
            get;
            set;
        }
    
        /// <summary>
        /// 添加时间
        /// </summary>
    	[DataMember]
    	[DisplayName("添加时间")]
        public virtual Nullable<System.DateTime> CreateDate
        {
            get;
            set;
        }
    
        /// <summary>
        /// 景区ID（可多个）
        /// </summary>
    	[DataMember]
    	[DisplayName("景区ID（可多个）")]
        public virtual string ParkIDs
        {
            get;
            set;
        }
    
        /// <summary>
        /// 酒店ID（可多个，也可没有）
        /// </summary>
    	[DataMember]
    	[DisplayName("酒店ID（可多个，也可没有）")]
        public virtual string HotelIDs
        {
            get;
            set;
        }

        #endregion
    }
}
