//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18033
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EditorLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditorLocalization() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.EditorLocalization", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Bold 的本地化字符串。
        /// </summary>
        internal static string Bold {
            get {
                return ResourceManager.GetString("Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert hyperlink 的本地化字符串。
        /// </summary>
        internal static string CreateLink {
            get {
                return ResourceManager.GetString("CreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete &quot;{0}&quot;? 的本地化字符串。
        /// </summary>
        internal static string DeleteFile {
            get {
                return ResourceManager.GetString("DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A directory with this name was not found. 的本地化字符串。
        /// </summary>
        internal static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty Folder 的本地化字符串。
        /// </summary>
        internal static string EmptyFolder {
            get {
                return ResourceManager.GetString("EmptyFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select font family 的本地化字符串。
        /// </summary>
        internal static string FontName {
            get {
                return ResourceManager.GetString("FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (inherited font) 的本地化字符串。
        /// </summary>
        internal static string FontNameInherit {
            get {
                return ResourceManager.GetString("FontNameInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select font size 的本地化字符串。
        /// </summary>
        internal static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (inherited size) 的本地化字符串。
        /// </summary>
        internal static string FontSizeInherit {
            get {
                return ResourceManager.GetString("FontSizeInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select block type 的本地化字符串。
        /// </summary>
        internal static string FormatBlock {
            get {
                return ResourceManager.GetString("FormatBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indent 的本地化字符串。
        /// </summary>
        internal static string Indent {
            get {
                return ResourceManager.GetString("Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert HTML 的本地化字符串。
        /// </summary>
        internal static string InsertHtml {
            get {
                return ResourceManager.GetString("InsertHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert image 的本地化字符串。
        /// </summary>
        internal static string InsertImage {
            get {
                return ResourceManager.GetString("InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert ordered list 的本地化字符串。
        /// </summary>
        internal static string InsertOrderedList {
            get {
                return ResourceManager.GetString("InsertOrderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert unordered list 的本地化字符串。
        /// </summary>
        internal static string InsertUnorderedList {
            get {
                return ResourceManager.GetString("InsertUnorderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selected file \&quot;{0}\&quot; is not valid. Supported file types are {1}. 的本地化字符串。
        /// </summary>
        internal static string InvalidFileType {
            get {
                return ResourceManager.GetString("InvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Italic 的本地化字符串。
        /// </summary>
        internal static string Italic {
            get {
                return ResourceManager.GetString("Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center text 的本地化字符串。
        /// </summary>
        internal static string JustifyCenter {
            get {
                return ResourceManager.GetString("JustifyCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Justify 的本地化字符串。
        /// </summary>
        internal static string JustifyFull {
            get {
                return ResourceManager.GetString("JustifyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align text left 的本地化字符串。
        /// </summary>
        internal static string JustifyLeft {
            get {
                return ResourceManager.GetString("JustifyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align text right 的本地化字符串。
        /// </summary>
        internal static string JustifyRight {
            get {
                return ResourceManager.GetString("JustifyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arrange by: 的本地化字符串。
        /// </summary>
        internal static string OrderBy {
            get {
                return ResourceManager.GetString("OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string OrderByName {
            get {
                return ResourceManager.GetString("OrderByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        internal static string OrderBySize {
            get {
                return ResourceManager.GetString("OrderBySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Outdent 的本地化字符串。
        /// </summary>
        internal static string Outdent {
            get {
                return ResourceManager.GetString("Outdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;A file with name &quot;{0}&quot; already exists in the current directory. Do you want to overwrite it? 的本地化字符串。
        /// </summary>
        internal static string OverwriteFile {
            get {
                return ResourceManager.GetString("OverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strikethrough 的本地化字符串。
        /// </summary>
        internal static string Strikethrough {
            get {
                return ResourceManager.GetString("Strikethrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Styles 的本地化字符串。
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Underline 的本地化字符串。
        /// </summary>
        internal static string Underline {
            get {
                return ResourceManager.GetString("Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove hyperlink 的本地化字符串。
        /// </summary>
        internal static string Unlink {
            get {
                return ResourceManager.GetString("Unlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload 的本地化字符串。
        /// </summary>
        internal static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
    }
}
