//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18033
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GridLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GridLocalization() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GridLocalization", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add new record 的本地化字符串。
        /// </summary>
        internal static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel changes 的本地化字符串。
        /// </summary>
        internal static string CancelChanges {
            get {
                return ResourceManager.GetString("CancelChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete this record? 的本地化字符串。
        /// </summary>
        internal static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Displaying items {0} - {1} of {2} 的本地化字符串。
        /// </summary>
        internal static string DisplayingItems {
            get {
                return ResourceManager.GetString("DisplayingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter 的本地化字符串。
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 And 的本地化字符串。
        /// </summary>
        internal static string FilterAnd {
            get {
                return ResourceManager.GetString("FilterAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is false 的本地化字符串。
        /// </summary>
        internal static string FilterBoolIsFalse {
            get {
                return ResourceManager.GetString("FilterBoolIsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is true 的本地化字符串。
        /// </summary>
        internal static string FilterBoolIsTrue {
            get {
                return ResourceManager.GetString("FilterBoolIsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Filter 的本地化字符串。
        /// </summary>
        internal static string FilterClear {
            get {
                return ResourceManager.GetString("FilterClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is equal to 的本地化字符串。
        /// </summary>
        internal static string FilterDateEq {
            get {
                return ResourceManager.GetString("FilterDateEq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is after or equal to 的本地化字符串。
        /// </summary>
        internal static string FilterDateGe {
            get {
                return ResourceManager.GetString("FilterDateGe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is after 的本地化字符串。
        /// </summary>
        internal static string FilterDateGt {
            get {
                return ResourceManager.GetString("FilterDateGt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is before or equal to 的本地化字符串。
        /// </summary>
        internal static string FilterDateLe {
            get {
                return ResourceManager.GetString("FilterDateLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is before 的本地化字符串。
        /// </summary>
        internal static string FilterDateLt {
            get {
                return ResourceManager.GetString("FilterDateLt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is not equal to 的本地化字符串。
        /// </summary>
        internal static string FilterDateNe {
            get {
                return ResourceManager.GetString("FilterDateNe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is equal to 的本地化字符串。
        /// </summary>
        internal static string FilterEnumEq {
            get {
                return ResourceManager.GetString("FilterEnumEq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is not equal to 的本地化字符串。
        /// </summary>
        internal static string FilterEnumNe {
            get {
                return ResourceManager.GetString("FilterEnumNe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is equal to 的本地化字符串。
        /// </summary>
        internal static string FilterForeignKeyEq {
            get {
                return ResourceManager.GetString("FilterForeignKeyEq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is not equal to 的本地化字符串。
        /// </summary>
        internal static string FilterForeignKeyNe {
            get {
                return ResourceManager.GetString("FilterForeignKeyNe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is equal to 的本地化字符串。
        /// </summary>
        internal static string FilterNumberEq {
            get {
                return ResourceManager.GetString("FilterNumberEq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is greater than or equal to 的本地化字符串。
        /// </summary>
        internal static string FilterNumberGe {
            get {
                return ResourceManager.GetString("FilterNumberGe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is greater than 的本地化字符串。
        /// </summary>
        internal static string FilterNumberGt {
            get {
                return ResourceManager.GetString("FilterNumberGt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is less than or equal to 的本地化字符串。
        /// </summary>
        internal static string FilterNumberLe {
            get {
                return ResourceManager.GetString("FilterNumberLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is less than 的本地化字符串。
        /// </summary>
        internal static string FilterNumberLt {
            get {
                return ResourceManager.GetString("FilterNumberLt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is not equal to 的本地化字符串。
        /// </summary>
        internal static string FilterNumberNe {
            get {
                return ResourceManager.GetString("FilterNumberNe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Or 的本地化字符串。
        /// </summary>
        internal static string FilterOr {
            get {
                return ResourceManager.GetString("FilterOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -Select value- 的本地化字符串。
        /// </summary>
        internal static string FilterSelectValue {
            get {
                return ResourceManager.GetString("FilterSelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show rows with value that 的本地化字符串。
        /// </summary>
        internal static string FilterShowRows {
            get {
                return ResourceManager.GetString("FilterShowRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ends with 的本地化字符串。
        /// </summary>
        internal static string FilterStringEndsWith {
            get {
                return ResourceManager.GetString("FilterStringEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is equal to 的本地化字符串。
        /// </summary>
        internal static string FilterStringEq {
            get {
                return ResourceManager.GetString("FilterStringEq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is not equal to 的本地化字符串。
        /// </summary>
        internal static string FilterStringNe {
            get {
                return ResourceManager.GetString("FilterStringNe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Does not contain 的本地化字符串。
        /// </summary>
        internal static string FilterStringNotSubstringOf {
            get {
                return ResourceManager.GetString("FilterStringNotSubstringOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starts with 的本地化字符串。
        /// </summary>
        internal static string FilterStringStartsWith {
            get {
                return ResourceManager.GetString("FilterStringStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contains 的本地化字符串。
        /// </summary>
        internal static string FilterStringSubstringOf {
            get {
                return ResourceManager.GetString("FilterStringSubstringOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag a column header and drop it here to group by that column 的本地化字符串。
        /// </summary>
        internal static string GroupHint {
            get {
                return ResourceManager.GetString("GroupHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert 的本地化字符串。
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No records to display. 的本地化字符串。
        /// </summary>
        internal static string NoRecords {
            get {
                return ResourceManager.GetString("NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page  的本地化字符串。
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 of {0} 的本地化字符串。
        /// </summary>
        internal static string PageOf {
            get {
                return ResourceManager.GetString("PageOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save changes 的本地化字符串。
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sorted ascending 的本地化字符串。
        /// </summary>
        internal static string SortedAsc {
            get {
                return ResourceManager.GetString("SortedAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sorted descending 的本地化字符串。
        /// </summary>
        internal static string SortedDesc {
            get {
                return ResourceManager.GetString("SortedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ungroup 的本地化字符串。
        /// </summary>
        internal static string UnGroup {
            get {
                return ResourceManager.GetString("UnGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
