//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// CrawlSightInfo
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.CrawlSightInfoDtoValidate))]
    public partial class CrawlSightInfoDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// ParkID
        /// </summary>
    	[DataMember]
    	[DisplayName("ParkID")]
        public virtual int ParkID
        {
            get;
            set;
        }
    
        /// <summary>
        /// Title
        /// </summary>
    	[DataMember]
    	[DisplayName("Title")]
        public virtual string Title
        {
            get;
            set;
        }
    
        /// <summary>
        /// ClassID
        /// </summary>
    	[DataMember]
    	[DisplayName("ClassID")]
        public virtual int ClassID
        {
            get;
            set;
        }
    
        /// <summary>
        /// FitCrowd
        /// </summary>
    	[DataMember]
    	[DisplayName("FitCrowd")]
        public virtual string FitCrowd
        {
            get;
            set;
        }
    
        /// <summary>
        /// Remark
        /// </summary>
    	[DataMember]
    	[DisplayName("Remark")]
        public virtual string Remark
        {
            get;
            set;
        }
    
        /// <summary>
        /// Url
        /// </summary>
    	[DataMember]
    	[DisplayName("Url")]
        public virtual string Url
        {
            get;
            set;
        }
    
        /// <summary>
        /// FileUrl
        /// </summary>
    	[DataMember]
    	[DisplayName("FileUrl")]
        public virtual string FileUrl
        {
            get;
            set;
        }
    
        /// <summary>
        /// VoIndex
        /// </summary>
    	[DataMember]
    	[DisplayName("VoIndex")]
        public virtual double VoIndex
        {
            get;
            set;
        }
    
        /// <summary>
        /// AdIndex
        /// </summary>
    	[DataMember]
    	[DisplayName("AdIndex")]
        public virtual double AdIndex
        {
            get;
            set;
        }
    
        /// <summary>
        /// ViCount
        /// </summary>
    	[DataMember]
    	[DisplayName("ViCount")]
        public virtual int ViCount
        {
            get;
            set;
        }
    
        /// <summary>
        /// Tag
        /// </summary>
    	[DataMember]
    	[DisplayName("Tag")]
        public virtual string Tag
        {
            get;
            set;
        }
    
        /// <summary>
        /// OpToTime
        /// </summary>
    	[DataMember]
    	[DisplayName("OpToTime")]
        public virtual string OpToTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// PicID
        /// </summary>
    	[DataMember]
    	[DisplayName("PicID")]
        public virtual Nullable<int> PicID
        {
            get;
            set;
        }
    
        /// <summary>
        /// PicPath
        /// </summary>
    	[DataMember]
    	[DisplayName("PicPath")]
        public virtual string PicPath
        {
            get;
            set;
        }
    
        /// <summary>
        /// VideoID
        /// </summary>
    	[DataMember]
    	[DisplayName("VideoID")]
        public virtual Nullable<int> VideoID
        {
            get;
            set;
        }
    
        /// <summary>
        /// VideoPath
        /// </summary>
    	[DataMember]
    	[DisplayName("VideoPath")]
        public virtual string VideoPath
        {
            get;
            set;
        }
    
        /// <summary>
        /// CommCount
        /// </summary>
    	[DataMember]
    	[DisplayName("CommCount")]
        public virtual Nullable<int> CommCount
        {
            get;
            set;
        }
    
        /// <summary>
        /// Blemish
        /// </summary>
    	[DataMember]
    	[DisplayName("Blemish")]
        public virtual string Blemish
        {
            get;
            set;
        }
    
        /// <summary>
        /// Province
        /// </summary>
    	[DataMember]
    	[DisplayName("Province")]
        public virtual string Province
        {
            get;
            set;
        }
    
        /// <summary>
        /// City
        /// </summary>
    	[DataMember]
    	[DisplayName("City")]
        public virtual string City
        {
            get;
            set;
        }
    
        /// <summary>
        /// InSource
        /// </summary>
    	[DataMember]
    	[DisplayName("InSource")]
        public virtual string InSource
        {
            get;
            set;
        }
    
        /// <summary>
        /// InAuthor
        /// </summary>
    	[DataMember]
    	[DisplayName("InAuthor")]
        public virtual string InAuthor
        {
            get;
            set;
        }
    
        /// <summary>
        /// UserID
        /// </summary>
    	[DataMember]
    	[DisplayName("UserID")]
        public virtual int UserID
        {
            get;
            set;
        }
    
        /// <summary>
        /// AddTime
        /// </summary>
    	[DataMember]
    	[DisplayName("AddTime")]
        public virtual System.DateTime AddTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// Aud
        /// </summary>
    	[DataMember]
    	[DisplayName("Aud")]
        public virtual int Aud
        {
            get;
            set;
        }
    
        /// <summary>
        /// Generalize
        /// </summary>
    	[DataMember]
    	[DisplayName("Generalize")]
        public virtual int Generalize
        {
            get;
            set;
        }
    
        /// <summary>
        /// GeBeTime
        /// </summary>
    	[DataMember]
    	[DisplayName("GeBeTime")]
        public virtual Nullable<System.DateTime> GeBeTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// GeEnTime
        /// </summary>
    	[DataMember]
    	[DisplayName("GeEnTime")]
        public virtual Nullable<System.DateTime> GeEnTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// MeIndex
        /// </summary>
    	[DataMember]
    	[DisplayName("MeIndex")]
        public virtual double MeIndex
        {
            get;
            set;
        }
    
        /// <summary>
        /// IsDelete
        /// </summary>
    	[DataMember]
    	[DisplayName("IsDelete")]
        public virtual int IsDelete
        {
            get;
            set;
        }
    
        /// <summary>
        /// DeTime
        /// </summary>
    	[DataMember]
    	[DisplayName("DeTime")]
        public virtual Nullable<System.DateTime> DeTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// OneSentence
        /// </summary>
    	[DataMember]
    	[DisplayName("OneSentence")]
        public virtual string OneSentence
        {
            get;
            set;
        }
    
        /// <summary>
        /// TrafficClew
        /// </summary>
    	[DataMember]
    	[DisplayName("TrafficClew")]
        public virtual string TrafficClew
        {
            get;
            set;
        }
    
        /// <summary>
        /// Telephone
        /// </summary>
    	[DataMember]
    	[DisplayName("Telephone")]
        public virtual string Telephone
        {
            get;
            set;
        }
    
        /// <summary>
        /// Email
        /// </summary>
    	[DataMember]
    	[DisplayName("Email")]
        public virtual string Email
        {
            get;
            set;
        }
    
        /// <summary>
        /// Fax
        /// </summary>
    	[DataMember]
    	[DisplayName("Fax")]
        public virtual string Fax
        {
            get;
            set;
        }
    
        /// <summary>
        /// VideoImg
        /// </summary>
    	[DataMember]
    	[DisplayName("VideoImg")]
        public virtual string VideoImg
        {
            get;
            set;
        }
    
        /// <summary>
        /// AudTime
        /// </summary>
    	[DataMember]
    	[DisplayName("AudTime")]
        public virtual Nullable<System.DateTime> AudTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// Boost
        /// </summary>
    	[DataMember]
    	[DisplayName("Boost")]
        public virtual Nullable<double> Boost
        {
            get;
            set;
        }
    
        /// <summary>
        /// ShopHours
        /// </summary>
    	[DataMember]
    	[DisplayName("ShopHours")]
        public virtual string ShopHours
        {
            get;
            set;
        }
    
        /// <summary>
        /// GoCount
        /// </summary>
    	[DataMember]
    	[DisplayName("GoCount")]
        public virtual Nullable<int> GoCount
        {
            get;
            set;
        }
    
        /// <summary>
        /// WantCount
        /// </summary>
    	[DataMember]
    	[DisplayName("WantCount")]
        public virtual Nullable<int> WantCount
        {
            get;
            set;
        }
    
        /// <summary>
        /// IsRegister
        /// </summary>
    	[DataMember]
    	[DisplayName("IsRegister")]
        public virtual Nullable<int> IsRegister
        {
            get;
            set;
        }
    
        /// <summary>
        /// ParkMap
        /// </summary>
    	[DataMember]
    	[DisplayName("ParkMap")]
        public virtual string ParkMap
        {
            get;
            set;
        }
    
        /// <summary>
        /// ParkingSpace
        /// </summary>
    	[DataMember]
    	[DisplayName("ParkingSpace")]
        public virtual string ParkingSpace
        {
            get;
            set;
        }
    
        /// <summary>
        /// Address
        /// </summary>
    	[DataMember]
    	[DisplayName("Address")]
        public virtual string Address
        {
            get;
            set;
        }
    
        /// <summary>
        /// YesWantCount
        /// </summary>
    	[DataMember]
    	[DisplayName("YesWantCount")]
        public virtual Nullable<int> YesWantCount
        {
            get;
            set;
        }
    
        /// <summary>
        /// YesGoCount
        /// </summary>
    	[DataMember]
    	[DisplayName("YesGoCount")]
        public virtual Nullable<int> YesGoCount
        {
            get;
            set;
        }
    
        /// <summary>
        /// YesViCount
        /// </summary>
    	[DataMember]
    	[DisplayName("YesViCount")]
        public virtual Nullable<int> YesViCount
        {
            get;
            set;
        }
    
        /// <summary>
        /// SiteUrl
        /// </summary>
    	[DataMember]
    	[DisplayName("SiteUrl")]
        public virtual string SiteUrl
        {
            get;
            set;
        }
    
        /// <summary>
        /// Popularity
        /// </summary>
    	[DataMember]
    	[DisplayName("Popularity")]
        public virtual Nullable<int> Popularity
        {
            get;
            set;
        }
    
        /// <summary>
        /// Latitude
        /// </summary>
    	[DataMember]
    	[DisplayName("Latitude")]
        public virtual Nullable<double> Latitude
        {
            get;
            set;
        }
    
        /// <summary>
        /// Longitude
        /// </summary>
    	[DataMember]
    	[DisplayName("Longitude")]
        public virtual Nullable<double> Longitude
        {
            get;
            set;
        }
    
        /// <summary>
        /// PY
        /// </summary>
    	[DataMember]
    	[DisplayName("PY")]
        public virtual string PY
        {
            get;
            set;
        }
    
        /// <summary>
        /// CirHotelID
        /// </summary>
    	[DataMember]
    	[DisplayName("CirHotelID")]
        public virtual string CirHotelID
        {
            get;
            set;
        }
    
        /// <summary>
        /// CirParkID
        /// </summary>
    	[DataMember]
    	[DisplayName("CirParkID")]
        public virtual string CirParkID
        {
            get;
            set;
        }
    
        /// <summary>
        /// CommHtml
        /// </summary>
    	[DataMember]
    	[DisplayName("CommHtml")]
        public virtual Nullable<bool> CommHtml
        {
            get;
            set;
        }
    
        /// <summary>
        /// Ticket
        /// </summary>
    	[DataMember]
    	[DisplayName("Ticket")]
        public virtual Nullable<int> Ticket
        {
            get;
            set;
        }
    
        /// <summary>
        /// VouchCount
        /// </summary>
    	[DataMember]
    	[DisplayName("VouchCount")]
        public virtual Nullable<int> VouchCount
        {
            get;
            set;
        }
    
        /// <summary>
        /// VouchValue
        /// </summary>
    	[DataMember]
    	[DisplayName("VouchValue")]
        public virtual Nullable<int> VouchValue
        {
            get;
            set;
        }
    
        /// <summary>
        /// AreaCode
        /// </summary>
    	[DataMember]
    	[DisplayName("AreaCode")]
        public virtual string AreaCode
        {
            get;
            set;
        }
    
        /// <summary>
        /// IsProcess
        /// </summary>
    	[DataMember]
    	[DisplayName("IsProcess")]
        public virtual string IsProcess
        {
            get;
            set;
        }

        #endregion
    }
}
