//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// 留言板表
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_GuestBookDtoValidate))]
    public partial class Sys_GuestBookDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// Id号
        /// </summary>
    	[DataMember]
    	[DisplayName("Id号")]
        public virtual int ID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 留言内容
        /// </summary>
    	[DataMember]
    	[DisplayName("留言内容")]
        public virtual string Content
        {
            get;
            set;
        }
    
        /// <summary>
        /// 留言Ip
        /// </summary>
    	[DataMember]
    	[DisplayName("留言Ip")]
        public virtual string Ip
        {
            get;
            set;
        }
    
        /// <summary>
        /// 添加时间
        /// </summary>
    	[DataMember]
    	[DisplayName("添加时间")]
        public virtual Nullable<System.DateTime> AddTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 用户名
        /// </summary>
    	[DataMember]
    	[DisplayName("用户名")]
        public virtual string UserName
        {
            get;
            set;
        }
    
        /// <summary>
        /// 用户Id
        /// </summary>
    	[DataMember]
    	[DisplayName("用户Id")]
        public virtual Nullable<int> UserID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 邮箱
        /// </summary>
    	[DataMember]
    	[DisplayName("邮箱")]
        public virtual string Email
        {
            get;
            set;
        }

        #endregion
    }
}
