//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// Sys_PicComm
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_PicCommDtoValidate))]
    public partial class Sys_PicCommDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// 图片评论
        /// </summary>
    	[DataMember]
    	[DisplayName("图片评论")]
        public virtual int CommID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 用户ID
        /// </summary>
    	[DataMember]
    	[DisplayName("用户ID")]
        public virtual int UserID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 用户名称
        /// </summary>
    	[DataMember]
    	[DisplayName("用户名称")]
        public virtual string UserName
        {
            get;
            set;
        }
    
        /// <summary>
        /// 图片ID
        /// </summary>
    	[DataMember]
    	[DisplayName("图片ID")]
        public virtual int PicID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 内容
        /// </summary>
    	[DataMember]
    	[DisplayName("内容")]
        public virtual string Content
        {
            get;
            set;
        }
    
        /// <summary>
        /// IP地址
        /// </summary>
    	[DataMember]
    	[DisplayName("IP地址")]
        public virtual string Ip
        {
            get;
            set;
        }
    
        /// <summary>
        /// 
        /// </summary>
    	[DataMember]
    	[DisplayName("添加时间")]
        public virtual System.DateTime AddTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 评论分
        /// </summary>
    	[DataMember]
    	[DisplayName("评论分")]
        public virtual int Fen
        {
            get;
            set;
        }

        #endregion
    }
}
