//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// Sys_ClientActivity
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_ClientActivityDtoValidate))]
    public partial class Sys_ClientActivityDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// ActivityID
        /// </summary>
    	[DataMember]
    	[DisplayName("ActivityID")]
        public virtual int ActivityID
        {
            get;
            set;
        }
    
        /// <summary>
        /// Ac_Name
        /// </summary>
    	[DataMember]
    	[DisplayName("Ac_Name")]
        public virtual string Ac_Name
        {
            get;
            set;
        }
    
        /// <summary>
        /// Ac_Url
        /// </summary>
    	[DataMember]
    	[DisplayName("Ac_Url")]
        public virtual string Ac_Url
        {
            get;
            set;
        }
    
        /// <summary>
        /// Ac_Visits
        /// </summary>
    	[DataMember]
    	[DisplayName("Ac_Visits")]
        public virtual Nullable<int> Ac_Visits
        {
            get;
            set;
        }
    
        /// <summary>
        /// Ac_Wants
        /// </summary>
    	[DataMember]
    	[DisplayName("Ac_Wants")]
        public virtual Nullable<int> Ac_Wants
        {
            get;
            set;
        }
    
        /// <summary>
        /// SightID
        /// </summary>
    	[DataMember]
    	[DisplayName("SightID")]
        public virtual Nullable<int> SightID
        {
            get;
            set;
        }
    
        /// <summary>
        /// Ac_Remak
        /// </summary>
    	[DataMember]
    	[DisplayName("Ac_Remak")]
        public virtual string Ac_Remak
        {
            get;
            set;
        }
    
        /// <summary>
        /// AddTime
        /// </summary>
    	[DataMember]
    	[DisplayName("AddTime")]
        public virtual Nullable<System.DateTime> AddTime
        {
            get;
            set;
        }

        #endregion
    }
}
