//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// Sys_AdWebsiteInfo
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_AdWebsiteInfoDtoValidate))]
    public partial class Sys_AdWebsiteInfoDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// WebID
        /// </summary>
    	[DataMember]
    	[DisplayName("WebID")]
        public virtual int WebID
        {
            get;
            set;
        }
    
        /// <summary>
        /// WebName
        /// </summary>
    	[DataMember]
    	[DisplayName("WebName")]
        public virtual string WebName
        {
            get;
            set;
        }
    
        /// <summary>
        /// Url
        /// </summary>
    	[DataMember]
    	[DisplayName("Url")]
        public virtual string Url
        {
            get;
            set;
        }
    
        /// <summary>
        /// LinkMan
        /// </summary>
    	[DataMember]
    	[DisplayName("LinkMan")]
        public virtual string LinkMan
        {
            get;
            set;
        }
    
        /// <summary>
        /// Email
        /// </summary>
    	[DataMember]
    	[DisplayName("Email")]
        public virtual string Email
        {
            get;
            set;
        }

        #endregion
    }
}
