//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// 用户扩展表
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_AdminUserExtensionDtoValidate))]
    public partial class Sys_AdminUserExtensionDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// Id号
        /// </summary>
    	[DataMember]
    	[DisplayName("Id号")]
        public virtual int Id
        {
            get;
            set;
        }
    
        /// <summary>
        /// 用户Id
        /// </summary>
    	[DataMember]
    	[DisplayName("用户Id")]
        public virtual int UserId
        {
            get;
            set;
        }
    
        /// <summary>
        /// 新浪微薄Id
        /// </summary>
    	[DataMember]
    	[DisplayName("新浪微薄Id")]
        public virtual string SinaId
        {
            get;
            set;
        }
    
        /// <summary>
        /// 新浪微薄显示名
        /// </summary>
    	[DataMember]
    	[DisplayName("新浪微薄显示名")]
        public virtual string SinaScreenName
        {
            get;
            set;
        }
    
        /// <summary>
        /// 新浪Token
        /// </summary>
    	[DataMember]
    	[DisplayName("新浪Token")]
        public virtual string SinaAccessToken
        {
            get;
            set;
        }
    
        /// <summary>
        /// 新浪TokenSecret
        /// </summary>
    	[DataMember]
    	[DisplayName("新浪TokenSecret")]
        public virtual string SinaAccessTokenSecret
        {
            get;
            set;
        }
    
        /// <summary>
        /// 腾讯微薄Id
        /// </summary>
    	[DataMember]
    	[DisplayName("腾讯微薄Id")]
        public virtual string QQId
        {
            get;
            set;
        }
    
        /// <summary>
        /// 腾讯微薄显示名
        /// </summary>
    	[DataMember]
    	[DisplayName("腾讯微薄显示名")]
        public virtual string QQScreenName
        {
            get;
            set;
        }
    
        /// <summary>
        /// 腾讯Token
        /// </summary>
    	[DataMember]
    	[DisplayName("腾讯Token")]
        public virtual string TenecntAccessToken
        {
            get;
            set;
        }
    
        /// <summary>
        /// 腾讯TokenSecret
        /// </summary>
    	[DataMember]
    	[DisplayName("腾讯TokenSecret")]
        public virtual string TenecntAccessTokenSecret
        {
            get;
            set;
        }
    
        /// <summary>
        /// 排序号
        /// </summary>
    	[DataMember]
    	[DisplayName("排序号")]
        public virtual Nullable<int> Sort
        {
            get;
            set;
        }
    
        /// <summary>
        /// 添加时间
        /// </summary>
    	[DataMember]
    	[DisplayName("添加时间")]
        public virtual Nullable<System.DateTime> AddTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 状态
        /// </summary>
    	[DataMember]
    	[DisplayName("状态")]
        public virtual Nullable<bool> State
        {
            get;
            set;
        }

        #endregion
    }
}
