//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// 友情链接分类表
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_LinksClassDtoValidate))]
    public partial class Sys_LinksClassDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// 分类ID号
        /// </summary>
    	[DataMember]
    	[DisplayName("分类ID号")]
        public virtual int ClassID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 分类名
        /// </summary>
    	[DataMember]
    	[DisplayName("分类名")]
        public virtual string ClassName
        {
            get;
            set;
        }
    
        /// <summary>
        /// 所属父ID
        /// </summary>
    	[DataMember]
    	[DisplayName("所属父ID")]
        public virtual Nullable<int> ParentID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 分类路径
        /// </summary>
    	[DataMember]
    	[DisplayName("分类路径")]
        public virtual string ClassPath
        {
            get;
            set;
        }
    
        /// <summary>
        /// 分类深度
        /// </summary>
    	[DataMember]
    	[DisplayName("分类深度")]
        public virtual Nullable<int> ClassDepth
        {
            get;
            set;
        }
    
        /// <summary>
        /// 分类排序
        /// </summary>
    	[DataMember]
    	[DisplayName("分类排序")]
        public virtual Nullable<int> ClassOrder
        {
            get;
            set;
        }
    
        /// <summary>
        /// 分类栏目
        /// </summary>
    	[DataMember]
    	[DisplayName("分类栏目")]
        public virtual string ClassIntro
        {
            get;
            set;
        }
    
        /// <summary>
        /// 模板ID
        /// </summary>
    	[DataMember]
    	[DisplayName("模板ID")]
        public virtual Nullable<int> DemoID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 是否删除
        /// </summary>
    	[DataMember]
    	[DisplayName("是否删除")]
        public virtual Nullable<int> IsDelete
        {
            get;
            set;
        }

        #endregion
    }
}
