//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// 模板表
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_DemoInfoDtoValidate))]
    public partial class Sys_DemoInfoDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// DemoID
        /// </summary>
    	[DataMember]
    	[DisplayName("DemoID")]
        public virtual int DemoID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 排序号
        /// </summary>
    	[DataMember]
    	[DisplayName("排序号")]
        public virtual int Sort
        {
            get;
            set;
        }
    
        /// <summary>
        /// 模板名
        /// </summary>
    	[DataMember]
    	[DisplayName("模板名")]
        public virtual string Title
        {
            get;
            set;
        }
    
        /// <summary>
        /// 模板内容
        /// </summary>
    	[DataMember]
    	[DisplayName("模板内容")]
        public virtual string Content
        {
            get;
            set;
        }
    
        /// <summary>
        /// 分类Id
        /// </summary>
    	[DataMember]
    	[DisplayName("分类Id")]
        public virtual int ClassID
        {
            get;
            set;
        }

        #endregion
    }
}
