//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// Sys_HotelReservationInfo
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_HotelReservationInfoDtoValidate))]
    public partial class Sys_HotelReservationInfoDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// confnum
        /// </summary>
    	[DataMember]
    	[DisplayName("confnum")]
        public virtual string confnum
        {
            get;
            set;
        }
    
        /// <summary>
        /// bookdate
        /// </summary>
    	[DataMember]
    	[DisplayName("bookdate")]
        public virtual Nullable<System.DateTime> bookdate
        {
            get;
            set;
        }
    
        /// <summary>
        /// status
        /// </summary>
    	[DataMember]
    	[DisplayName("status")]
        public virtual string status
        {
            get;
            set;
        }
    
        /// <summary>
        /// cxlnum
        /// </summary>
    	[DataMember]
    	[DisplayName("cxlnum")]
        public virtual string cxlnum
        {
            get;
            set;
        }
    
        /// <summary>
        /// arrival
        /// </summary>
    	[DataMember]
    	[DisplayName("arrival")]
        public virtual Nullable<System.DateTime> arrival
        {
            get;
            set;
        }
    
        /// <summary>
        /// departure
        /// </summary>
    	[DataMember]
    	[DisplayName("departure")]
        public virtual Nullable<System.DateTime> departure
        {
            get;
            set;
        }
    
        /// <summary>
        /// planid
        /// </summary>
    	[DataMember]
    	[DisplayName("planid")]
        public virtual string planid
        {
            get;
            set;
        }
    
        /// <summary>
        /// firstname
        /// </summary>
    	[DataMember]
    	[DisplayName("firstname")]
        public virtual string firstname
        {
            get;
            set;
        }
    
        /// <summary>
        /// PropID
        /// </summary>
    	[DataMember]
    	[DisplayName("PropID")]
        public virtual string PropID
        {
            get;
            set;
        }
    
        /// <summary>
        /// ningts
        /// </summary>
    	[DataMember]
    	[DisplayName("ningts")]
        public virtual string ningts
        {
            get;
            set;
        }
    
        /// <summary>
        /// roomtype
        /// </summary>
    	[DataMember]
    	[DisplayName("roomtype")]
        public virtual string roomtype
        {
            get;
            set;
        }
    
        /// <summary>
        /// rateclass
        /// </summary>
    	[DataMember]
    	[DisplayName("rateclass")]
        public virtual string rateclass
        {
            get;
            set;
        }
    
        /// <summary>
        /// rooms
        /// </summary>
    	[DataMember]
    	[DisplayName("rooms")]
        public virtual string rooms
        {
            get;
            set;
        }
    
        /// <summary>
        /// adults
        /// </summary>
    	[DataMember]
    	[DisplayName("adults")]
        public virtual string adults
        {
            get;
            set;
        }
    
        /// <summary>
        /// phone
        /// </summary>
    	[DataMember]
    	[DisplayName("phone")]
        public virtual string phone
        {
            get;
            set;
        }
    
        /// <summary>
        /// email
        /// </summary>
    	[DataMember]
    	[DisplayName("email")]
        public virtual string email
        {
            get;
            set;
        }
    
        /// <summary>
        /// remark
        /// </summary>
    	[DataMember]
    	[DisplayName("remark")]
        public virtual string remark
        {
            get;
            set;
        }
    
        /// <summary>
        /// cellphone
        /// </summary>
    	[DataMember]
    	[DisplayName("cellphone")]
        public virtual string cellphone
        {
            get;
            set;
        }
    
        /// <summary>
        /// isSendEmail
        /// </summary>
    	[DataMember]
    	[DisplayName("isSendEmail")]
        public virtual Nullable<int> isSendEmail
        {
            get;
            set;
        }

        #endregion
    }
}
