//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// 用户日志表
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_AdminUserLogDtoValidate))]
    public partial class Sys_AdminUserLogDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// Id号
        /// </summary>
    	[DataMember]
    	[DisplayName("Id号")]
        public virtual int Id
        {
            get;
            set;
        }
    
        /// <summary>
        /// 日志类型
        /// </summary>
    	[DataMember]
    	[DisplayName("日志类型")]
        public virtual Nullable<int> TypeId
        {
            get;
            set;
        }
    
        /// <summary>
        /// 用户Id
        /// </summary>
    	[DataMember]
    	[DisplayName("用户Id")]
        public virtual Nullable<int> UserId
        {
            get;
            set;
        }
    
        /// <summary>
        /// 操作Ip
        /// </summary>
    	[DataMember]
    	[DisplayName("操作Ip")]
        public virtual string IpAddress
        {
            get;
            set;
        }
    
        /// <summary>
        /// 访问页面
        /// </summary>
    	[DataMember]
    	[DisplayName("访问页面")]
        public virtual string PageUrl
        {
            get;
            set;
        }
    
        /// <summary>
        /// 访问上一页面
        /// </summary>
    	[DataMember]
    	[DisplayName("访问上一页面")]
        public virtual string ReferrerUrl
        {
            get;
            set;
        }
    
        /// <summary>
        /// 详细信息
        /// </summary>
    	[DataMember]
    	[DisplayName("详细信息")]
        public virtual string FullMessage
        {
            get;
            set;
        }
    
        /// <summary>
        /// 简介
        /// </summary>
    	[DataMember]
    	[DisplayName("简介")]
        public virtual string ShortMessage
        {
            get;
            set;
        }
    
        /// <summary>
        /// 添加时间
        /// </summary>
    	[DataMember]
    	[DisplayName("添加时间")]
        public virtual Nullable<System.DateTime> AddTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 状态
        /// </summary>
    	[DataMember]
    	[DisplayName("状态")]
        public virtual Nullable<bool> State
        {
            get;
            set;
        }

        #endregion
    }
}
