//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// Sys_MenuTree
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_MenuTreeDtoValidate))]
    public partial class Sys_MenuTreeDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// 节点ID
        /// </summary>
    	[DataMember]
    	[DisplayName("节点ID")]
        public virtual int NodeID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 文本
        /// </summary>
    	[DataMember]
    	[DisplayName("文本")]
        public virtual string Text
        {
            get;
            set;
        }
    
        /// <summary>
        /// 上级ID
        /// </summary>
    	[DataMember]
    	[DisplayName("上级ID")]
        public virtual int ParentID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 父节点
        /// </summary>
    	[DataMember]
    	[DisplayName("父节点")]
        public virtual string ParentPath
        {
            get;
            set;
        }
    
        /// <summary>
        /// 位置
        /// </summary>
    	[DataMember]
    	[DisplayName("位置")]
        public virtual string Location
        {
            get;
            set;
        }
    
        /// <summary>
        /// 排序
        /// </summary>
    	[DataMember]
    	[DisplayName("排序")]
        public virtual Nullable<int> OrderID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 评论
        /// </summary>
    	[DataMember]
    	[DisplayName("评论")]
        public virtual string comment
        {
            get;
            set;
        }
    
        /// <summary>
        /// URL
        /// </summary>
    	[DataMember]
    	[DisplayName("URL")]
        public virtual string Url
        {
            get;
            set;
        }
    
        /// <summary>
        /// 权限ID
        /// </summary>
    	[DataMember]
    	[DisplayName("权限ID")]
        public virtual Nullable<int> PermissionID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 图片URL
        /// </summary>
    	[DataMember]
    	[DisplayName("图片URL")]
        public virtual string ImageUrl
        {
            get;
            set;
        }
    
        /// <summary>
        /// 模块ID
        /// </summary>
    	[DataMember]
    	[DisplayName("模块ID")]
        public virtual Nullable<int> ModuleID
        {
            get;
            set;
        }
    
        /// <summary>
        /// KeShiDM
        /// </summary>
    	[DataMember]
    	[DisplayName("KeShiDM")]
        public virtual Nullable<int> KeShiDM
        {
            get;
            set;
        }
    
        /// <summary>
        /// KeshiPublic
        /// </summary>
    	[DataMember]
    	[DisplayName("KeshiPublic")]
        public virtual string KeshiPublic
        {
            get;
            set;
        }
    
        /// <summary>
        /// 管理项
        /// </summary>
    	[DataMember]
    	[DisplayName("管理项")]
        public virtual string ManageOption
        {
            get;
            set;
        }

        #endregion
    }
}
