//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// Sys_TourPlan
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_TourPlanDtoValidate))]
    public partial class Sys_TourPlanDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// 旅游线路ID
        /// </summary>
    	[DataMember]
    	[DisplayName("旅游线路ID")]
        public virtual int PlanID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 旅游线路名
        /// </summary>
    	[DataMember]
    	[DisplayName("旅游线路名")]
        public virtual string PlanTitle
        {
            get;
            set;
        }
    
        /// <summary>
        /// 分类ID
        /// </summary>
    	[DataMember]
    	[DisplayName("分类ID")]
        public virtual Nullable<int> PlanClass
        {
            get;
            set;
        }
    
        /// <summary>
        /// 说明
        /// </summary>
    	[DataMember]
    	[DisplayName("说明")]
        public virtual string Remark
        {
            get;
            set;
        }
    
        /// <summary>
        /// 目的地
        /// </summary>
    	[DataMember]
    	[DisplayName("目的地")]
        public virtual string Destination
        {
            get;
            set;
        }
    
        /// <summary>
        /// 操作用户名
        /// </summary>
    	[DataMember]
    	[DisplayName("操作用户名")]
        public virtual string UserName
        {
            get;
            set;
        }
    
        /// <summary>
        /// 操作用户ID
        /// </summary>
    	[DataMember]
    	[DisplayName("操作用户ID")]
        public virtual Nullable<int> UserId
        {
            get;
            set;
        }
    
        /// <summary>
        /// 没有怎么用
        /// </summary>
    	[DataMember]
    	[DisplayName("没有怎么用")]
        public virtual Nullable<int> VisitCount
        {
            get;
            set;
        }
    
        /// <summary>
        /// 顶置理由
        /// </summary>
    	[DataMember]
    	[DisplayName("顶置理由")]
        public virtual string TopReason
        {
            get;
            set;
        }
    
        /// <summary>
        /// 顶置时间
        /// </summary>
    	[DataMember]
    	[DisplayName("顶置时间")]
        public virtual Nullable<System.DateTime> TopTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 数据库全为NULL
        /// </summary>
    	[DataMember]
    	[DisplayName("数据库全为NULL")]
        public virtual string TempDataCreateHtml
        {
            get;
            set;
        }
    
        /// <summary>
        /// 是否顶置
        /// </summary>
    	[DataMember]
    	[DisplayName("是否顶置")]
        public virtual Nullable<int> IsTop
        {
            get;
            set;
        }
    
        /// <summary>
        /// 时间
        /// </summary>
    	[DataMember]
    	[DisplayName("时间")]
        public virtual Nullable<int> Days
        {
            get;
            set;
        }
    
        /// <summary>
        /// 是否被删除
        /// </summary>
    	[DataMember]
    	[DisplayName("是否被删除")]
        public virtual Nullable<int> IsDelete
        {
            get;
            set;
        }
    
        /// <summary>
        /// 添加时间
        /// </summary>
    	[DataMember]
    	[DisplayName("添加时间")]
        public virtual Nullable<System.DateTime> AddTime
        {
            get;
            set;
        }

        #endregion
    }
}
