//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// 用户自定义扩展表
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_AdminUserIndividuationDtoValidate))]
    public partial class Sys_AdminUserIndividuationDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// Id号
        /// </summary>
    	[DataMember]
    	[DisplayName("Id号")]
        public virtual int Id
        {
            get;
            set;
        }
    
        /// <summary>
        /// 用户Id号
        /// </summary>
    	[DataMember]
    	[DisplayName("用户Id号")]
        public virtual Nullable<int> UserId
        {
            get;
            set;
        }
    
        /// <summary>
        /// 系统名(英文)
        /// </summary>
    	[DataMember]
    	[DisplayName("系统名")]
        public virtual string KeySysName
        {
            get;
            set;
        }
    
        /// <summary>
        /// 系统显示名
        /// </summary>
    	[DataMember]
    	[DisplayName("系统显示名")]
        public virtual string KeyNameScreenName
        {
            get;
            set;
        }
    
        /// <summary>
        /// 值
        /// </summary>
    	[DataMember]
    	[DisplayName("值")]
        public virtual string KeyValue
        {
            get;
            set;
        }
    
        /// <summary>
        /// 添加时间
        /// </summary>
    	[DataMember]
    	[DisplayName("添加时间")]
        public virtual Nullable<System.DateTime> AddTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 状态
        /// </summary>
    	[DataMember]
    	[DisplayName("状态")]
        public virtual Nullable<bool> State
        {
            get;
            set;
        }
    
        /// <summary>
        /// 排序号
        /// </summary>
    	[DataMember]
    	[DisplayName("排序号")]
        public virtual Nullable<int> Sort
        {
            get;
            set;
        }

        #endregion
    }
}
