//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// Sys_TourClass
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_TourClassDtoValidate))]
    public partial class Sys_TourClassDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// 旅行分类ID
        /// </summary>
    	[DataMember]
    	[DisplayName("旅行分类ID")]
        public virtual int ClassID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 旅行分类名称
        /// </summary>
    	[DataMember]
    	[DisplayName("旅行分类名称")]
        public virtual string ClassName
        {
            get;
            set;
        }
    
        /// <summary>
        /// 父ID
        /// </summary>
    	[DataMember]
    	[DisplayName("父ID")]
        public virtual Nullable<int> ParentID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 分类路径
        /// </summary>
    	[DataMember]
    	[DisplayName("分类路径")]
        public virtual string ClassPath
        {
            get;
            set;
        }
    
        /// <summary>
        /// ClassDepth
        /// </summary>
    	[DataMember]
    	[DisplayName("ClassDepth")]
        public virtual Nullable<int> ClassDepth
        {
            get;
            set;
        }
    
        /// <summary>
        /// ClassOrder
        /// </summary>
    	[DataMember]
    	[DisplayName("ClassOrder")]
        public virtual Nullable<int> ClassOrder
        {
            get;
            set;
        }
    
        /// <summary>
        /// 说明
        /// </summary>
    	[DataMember]
    	[DisplayName("说明")]
        public virtual string ClassIntro
        {
            get;
            set;
        }
    
        /// <summary>
        /// 模板ID
        /// </summary>
    	[DataMember]
    	[DisplayName("模板ID")]
        public virtual Nullable<int> DemoID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 是否删除
        /// </summary>
    	[DataMember]
    	[DisplayName("是否删除")]
        public virtual Nullable<int> IsDelete
        {
            get;
            set;
        }

        #endregion
    }
}
