//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// 城市详细表
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_CityInfoMoreDtoValidate))]
    public partial class Sys_CityInfoMoreDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// Id号
        /// </summary>
    	[DataMember]
    	[DisplayName("Id号")]
        public virtual int Id
        {
            get;
            set;
        }
    
        /// <summary>
        /// 城市名
        /// </summary>
    	[DataMember]
    	[DisplayName("城市名")]
        public virtual string City
        {
            get;
            set;
        }
    
        /// <summary>
        /// 城市名全拼
        /// </summary>
    	[DataMember]
    	[DisplayName("城市名全拼")]
        public virtual string PinYin
        {
            get;
            set;
        }
    
        /// <summary>
        /// 缩拼
        /// </summary>
    	[DataMember]
    	[DisplayName("缩拼")]
        public virtual string Py
        {
            get;
            set;
        }
    
        /// <summary>
        /// 邮政编码
        /// </summary>
    	[DataMember]
    	[DisplayName("邮政编码")]
        public virtual string PostCode
        {
            get;
            set;
        }
    
        /// <summary>
        /// 所属省的所属区域比如说是华北
        /// </summary>
    	[DataMember]
    	[DisplayName("所属区域")]
        public virtual string AearName
        {
            get;
            set;
        }
    
        /// <summary>
        /// 纬度
        /// </summary>
    	[DataMember]
    	[DisplayName("纬度")]
        public virtual Nullable<double> Latitude
        {
            get;
            set;
        }
    
        /// <summary>
        /// 经度
        /// </summary>
    	[DataMember]
    	[DisplayName("经度")]
        public virtual Nullable<double> Longitude
        {
            get;
            set;
        }
    
        /// <summary>
        /// 省名
        /// </summary>
    	[DataMember]
    	[DisplayName("省名")]
        public virtual string Province
        {
            get;
            set;
        }
    
        /// <summary>
        /// 省拼音
        /// </summary>
    	[DataMember]
    	[DisplayName("省拼音")]
        public virtual string ProvincePy
        {
            get;
            set;
        }
    
        /// <summary>
        /// 添加时间
        /// </summary>
    	[DataMember]
    	[DisplayName("添加时间")]
        public virtual Nullable<System.DateTime> AddTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 状态
        /// </summary>
    	[DataMember]
    	[DisplayName("状态")]
        public virtual Nullable<bool> State
        {
            get;
            set;
        }

        #endregion
    }
}
