//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// Sys_NewsInfo
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_NewsInfoDtoValidate))]
    public partial class Sys_NewsInfoDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// 新闻ID
        /// </summary>
    	[DataMember]
    	[DisplayName("新闻ID")]
        public virtual int NewsId
        {
            get;
            set;
        }
    
        /// <summary>
        /// 标题
        /// </summary>
    	[DataMember]
    	[DisplayName("标题")]
        public virtual string Title
        {
            get;
            set;
        }
    
        /// <summary>
        /// 内容
        /// </summary>
    	[DataMember]
    	[DisplayName("内容")]
        public virtual string Content
        {
            get;
            set;
        }
    
        /// <summary>
        /// 来源
        /// </summary>
    	[DataMember]
    	[DisplayName("来源")]
        public virtual string Source
        {
            get;
            set;
        }
    
        /// <summary>
        /// 点击数
        /// </summary>
    	[DataMember]
    	[DisplayName("点击数")]
        public virtual Nullable<int> Hits
        {
            get;
            set;
        }
    
        /// <summary>
        /// 添加时间
        /// </summary>
    	[DataMember]
    	[DisplayName("添加时间")]
        public virtual Nullable<System.DateTime> AddTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 操作ID
        /// </summary>
    	[DataMember]
    	[DisplayName("操作ID")]
        public virtual Nullable<int> UserID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 是否删除
        /// </summary>
    	[DataMember]
    	[DisplayName("是否删除")]
        public virtual Nullable<int> IsDelete
        {
            get;
            set;
        }
    
        /// <summary>
        /// 删除时间
        /// </summary>
    	[DataMember]
    	[DisplayName("删除时间")]
        public virtual Nullable<System.DateTime> DeleteTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 景区ID
        /// </summary>
    	[DataMember]
    	[DisplayName("景区ID")]
        public virtual Nullable<int> SightID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 分类ID
        /// </summary>
    	[DataMember]
    	[DisplayName("分类ID")]
        public virtual Nullable<int> ClassID
        {
            get;
            set;
        }

        #endregion
    }
}
