//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// Sys_VouchHotelInfo
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_VouchHotelInfoDtoValidate))]
    public partial class Sys_VouchHotelInfoDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// 推荐ID
        /// </summary>
    	[DataMember]
    	[DisplayName("推荐ID")]
        public virtual int VouchID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 推荐城市
        /// </summary>
    	[DataMember]
    	[DisplayName("推荐城市")]
        public virtual string CityName
        {
            get;
            set;
        }
    
        /// <summary>
        /// 城市中推荐景区
        /// </summary>
    	[DataMember]
    	[DisplayName("城市中推荐景区")]
        public virtual string SightIDs
        {
            get;
            set;
        }
    
        /// <summary>
        /// 推荐景区名
        /// </summary>
    	[DataMember]
    	[DisplayName("推荐景区名")]
        public virtual string SightNames
        {
            get;
            set;
        }
    
        /// <summary>
        /// 添加时间
        /// </summary>
    	[DataMember]
    	[DisplayName("添加时间")]
        public virtual Nullable<System.DateTime> AddTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 推荐时间
        /// </summary>
    	[DataMember]
    	[DisplayName("推荐时间")]
        public virtual string VouchTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 推荐人ID
        /// </summary>
    	[DataMember]
    	[DisplayName("推荐人ID")]
        public virtual Nullable<int> UserID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 城市缩拼
        /// </summary>
    	[DataMember]
    	[DisplayName("城市缩拼")]
        public virtual string CityPy
        {
            get;
            set;
        }
    
        /// <summary>
        /// 城市全拼
        /// </summary>
    	[DataMember]
    	[DisplayName("城市全拼")]
        public virtual string CityQuanP
        {
            get;
            set;
        }

        #endregion
    }
}
