//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// 城市表
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_CityInfoDtoValidate))]
    public partial class Sys_CityInfoDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// 城市ID号
        /// </summary>
    	[DataMember]
    	[DisplayName("城市ID号")]
        public virtual int id
        {
            get;
            set;
        }
    
        /// <summary>
        /// 省名
        /// </summary>
    	[DataMember]
    	[DisplayName("省名")]
        public virtual string province
        {
            get;
            set;
        }
    
        /// <summary>
        /// 城市名
        /// </summary>
    	[DataMember]
    	[DisplayName("城市名")]
        public virtual string city
        {
            get;
            set;
        }
    
        /// <summary>
        /// 城市拼音
        /// </summary>
    	[DataMember]
    	[DisplayName("城市拼音")]
        public virtual string pinyin
        {
            get;
            set;
        }
    
        /// <summary>
        /// 纬度
        /// </summary>
    	[DataMember]
    	[DisplayName("纬度")]
        public virtual Nullable<double> Latitude
        {
            get;
            set;
        }
    
        /// <summary>
        /// 纬度
        /// </summary>
    	[DataMember]
    	[DisplayName("纬度")]
        public virtual Nullable<double> Longitude
        {
            get;
            set;
        }
    
        /// <summary>
        /// 缩拼
        /// </summary>
    	[DataMember]
    	[DisplayName("缩拼")]
        public virtual string py
        {
            get;
            set;
        }
    
        /// <summary>
        /// 省全拼
        /// </summary>
    	[DataMember]
    	[DisplayName("省全拼")]
        public virtual string ProvincePy
        {
            get;
            set;
        }

        #endregion
    }
}
