//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// Sys_TourInfo
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_TourInfoDtoValidate))]
    public partial class Sys_TourInfoDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// 路线ID
        /// </summary>
    	[DataMember]
    	[DisplayName("路线ID")]
        public virtual int TourID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 路线名
        /// </summary>
    	[DataMember]
    	[DisplayName("路线名")]
        public virtual string TourTitle
        {
            get;
            set;
        }
    
        /// <summary>
        /// 路线价格
        /// </summary>
    	[DataMember]
    	[DisplayName("路线价格")]
        public virtual Nullable<int> Price
        {
            get;
            set;
        }
    
        /// <summary>
        /// 分类ID
        /// </summary>
    	[DataMember]
    	[DisplayName("分类ID")]
        public virtual Nullable<int> ClassID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 路线说明
        /// </summary>
    	[DataMember]
    	[DisplayName("路线说明")]
        public virtual string Remark
        {
            get;
            set;
        }
    
        /// <summary>
        /// 一般没有用 都是0
        /// </summary>
    	[DataMember]
    	[DisplayName("一般没有用 都是0")]
        public virtual Nullable<int> VisitCount
        {
            get;
            set;
        }
    
        /// <summary>
        /// 路线定制用户名称
        /// </summary>
    	[DataMember]
    	[DisplayName("路线定制用户名称")]
        public virtual string Author
        {
            get;
            set;
        }
    
        /// <summary>
        /// 操作用户ID
        /// </summary>
    	[DataMember]
    	[DisplayName("操作用户ID")]
        public virtual Nullable<int> UserID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 路线天数
        /// </summary>
    	[DataMember]
    	[DisplayName("路线天数")]
        public virtual Nullable<int> Days
        {
            get;
            set;
        }
    
        /// <summary>
        /// 添加时间
        /// </summary>
    	[DataMember]
    	[DisplayName("添加时间")]
        public virtual Nullable<System.DateTime> AddTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 是否被删除
        /// </summary>
    	[DataMember]
    	[DisplayName("是否被删除")]
        public virtual Nullable<int> IsDelete
        {
            get;
            set;
        }
    
        /// <summary>
        /// 是否推荐
        /// </summary>
    	[DataMember]
    	[DisplayName("是否推荐")]
        public virtual Nullable<int> IsVouch
        {
            get;
            set;
        }
    
        /// <summary>
        /// 推荐时间
        /// </summary>
    	[DataMember]
    	[DisplayName("推荐时间")]
        public virtual Nullable<System.DateTime> VouchTime
        {
            get;
            set;
        }

        #endregion
    }
}
