//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// Sys_UserRoles
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_UserRolesDtoValidate))]
    public partial class Sys_UserRolesDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// 用户角色ID
        /// </summary>
    	[DataMember]
    	[DisplayName("用户角色ID")]
        public virtual int Id
        {
            get;
            set;
        }
    
        /// <summary>
        /// 用户ID
        /// </summary>
    	[DataMember]
    	[DisplayName("用户ID")]
        public virtual int UserID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 角色ID
        /// </summary>
    	[DataMember]
    	[DisplayName("角色ID")]
        public virtual int RoleID
        {
            get;
            set;
        }

        #endregion
    }
}
