//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// Sys_HotelRoomInfo
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_HotelRoomInfoDtoValidate))]
    public partial class Sys_HotelRoomInfoDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// HotelID
        /// </summary>
    	[DataMember]
    	[DisplayName("HotelID")]
        public virtual int HotelID
        {
            get;
            set;
        }
    
        /// <summary>
        /// RoomType
        /// </summary>
    	[DataMember]
    	[DisplayName("RoomType")]
        public virtual string RoomType
        {
            get;
            set;
        }
    
        /// <summary>
        /// HotelDescription
        /// </summary>
    	[DataMember]
    	[DisplayName("HotelDescription")]
        public virtual string HotelDescription
        {
            get;
            set;
        }
    
        /// <summary>
        /// PlanID
        /// </summary>
    	[DataMember]
    	[DisplayName("PlanID")]
        public virtual string PlanID
        {
            get;
            set;
        }
    
        /// <summary>
        /// PlanDescription
        /// </summary>
    	[DataMember]
    	[DisplayName("PlanDescription")]
        public virtual string PlanDescription
        {
            get;
            set;
        }
    
        /// <summary>
        /// RoomName
        /// </summary>
    	[DataMember]
    	[DisplayName("RoomName")]
        public virtual string RoomName
        {
            get;
            set;
        }
    
        /// <summary>
        /// MaxOccupancy
        /// </summary>
    	[DataMember]
    	[DisplayName("MaxOccupancy")]
        public virtual Nullable<int> MaxOccupancy
        {
            get;
            set;
        }

        #endregion
    }
}
