//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// 文章信息表
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_ArticleInfoDtoValidate))]
    public partial class Sys_ArticleInfoDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// 文章ID
        /// </summary>
    	[DataMember]
    	[DisplayName("文章ID")]
        public virtual int ArticleID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 分类Id
        /// </summary>
    	[DataMember]
    	[DisplayName("分类Id")]
        public virtual int ClassID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 添加用户Id
        /// </summary>
    	[DataMember]
    	[DisplayName("添加用户Id")]
        public virtual int UserID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 图片Id
        /// </summary>
    	[DataMember]
    	[DisplayName("图片Id")]
        public virtual int PicID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 图片地址
        /// </summary>
    	[DataMember]
    	[DisplayName("图片地址")]
        public virtual string PicUrl
        {
            get;
            set;
        }
    
        /// <summary>
        /// 主标题
        /// </summary>
    	[DataMember]
    	[DisplayName("主标题")]
        public virtual string Title
        {
            get;
            set;
        }
    
        /// <summary>
        /// 副标题
        /// </summary>
    	[DataMember]
    	[DisplayName("副标题")]
        public virtual string SubTitle
        {
            get;
            set;
        }
    
        /// <summary>
        /// 文章标签
        /// </summary>
    	[DataMember]
    	[DisplayName("文章标签")]
        public virtual string Tag
        {
            get;
            set;
        }
    
        /// <summary>
        /// 文章内容
        /// </summary>
    	[DataMember]
    	[DisplayName("文章内容")]
        public virtual string Content
        {
            get;
            set;
        }
    
        /// <summary>
        /// 评论数
        /// </summary>
    	[DataMember]
    	[DisplayName("评论数")]
        public virtual int CommFlag
        {
            get;
            set;
        }
    
        /// <summary>
        /// 添加时间
        /// </summary>
    	[DataMember]
    	[DisplayName("添加时间")]
        public virtual System.DateTime AddTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 访问量
        /// </summary>
    	[DataMember]
    	[DisplayName("访问量")]
        public virtual int VisitCount
        {
            get;
            set;
        }
    
        /// <summary>
        /// 是否顶置
        /// </summary>
    	[DataMember]
    	[DisplayName("是否顶置")]
        public virtual int IsTop
        {
            get;
            set;
        }
    
        /// <summary>
        /// 顶置时间
        /// </summary>
    	[DataMember]
    	[DisplayName("顶置时间")]
        public virtual Nullable<System.DateTime> TopTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 是否推荐
        /// </summary>
    	[DataMember]
    	[DisplayName("是否推荐")]
        public virtual int IsVouch
        {
            get;
            set;
        }
    
        /// <summary>
        /// 推荐时间
        /// </summary>
    	[DataMember]
    	[DisplayName("推荐时间")]
        public virtual Nullable<System.DateTime> VouchTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 是否删除
        /// </summary>
    	[DataMember]
    	[DisplayName("是否删除")]
        public virtual int IsDelete
        {
            get;
            set;
        }
    
        /// <summary>
        /// 是否审核
        /// </summary>
    	[DataMember]
    	[DisplayName("是否审核")]
        public virtual Nullable<int> IsAud
        {
            get;
            set;
        }
    
        /// <summary>
        /// 审核时间
        /// </summary>
    	[DataMember]
    	[DisplayName("审核时间")]
        public virtual Nullable<System.DateTime> AudTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 删除时间
        /// </summary>
    	[DataMember]
    	[DisplayName("删除时间")]
        public virtual Nullable<System.DateTime> DeleteTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 景点Id
        /// </summary>
    	[DataMember]
    	[DisplayName("景点Id")]
        public virtual Nullable<int> SightID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 文章地址(如果是采集的话)
        /// </summary>
    	[DataMember]
    	[DisplayName("文章地址")]
        public virtual string ArticleUrl
        {
            get;
            set;
        }
    
        /// <summary>
        /// 来源
        /// </summary>
    	[DataMember]
    	[DisplayName("来源")]
        public virtual string Source
        {
            get;
            set;
        }

        #endregion
    }
}
