//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// 优惠评论表
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_DiscountCommDtoValidate))]
    public partial class Sys_DiscountCommDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// 评论ID
        /// </summary>
    	[DataMember]
    	[DisplayName("评论ID")]
        public virtual int CommID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 优惠ID号
        /// </summary>
    	[DataMember]
    	[DisplayName("优惠ID号")]
        public virtual int DiscountID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 评论的父ID号（可以不用 0表不用 默认值 ）
        /// </summary>
    	[DataMember]
    	[DisplayName("所属父ID")]
        public virtual int ParentID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 用户ID号(0为游客)
        /// </summary>
    	[DataMember]
    	[DisplayName("用户ID号")]
        public virtual int UserID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 用户名
        /// </summary>
    	[DataMember]
    	[DisplayName("用户名")]
        public virtual string UserName
        {
            get;
            set;
        }
    
        /// <summary>
        /// 当接口开放出开的时候 用于存不同类型的用户  新浪微博 QQ 等
        /// </summary>
    	[DataMember]
    	[DisplayName("用户类型")]
        public virtual string UserType
        {
            get;
            set;
        }
    
        /// <summary>
        /// 评论内容
        /// </summary>
    	[DataMember]
    	[DisplayName("评论内容")]
        public virtual string Content
        {
            get;
            set;
        }
    
        /// <summary>
        /// 评论时客户端类型(电脑、手机类型)
        /// </summary>
    	[DataMember]
    	[DisplayName("客户端类型")]
        public virtual string ClientType
        {
            get;
            set;
        }
    
        /// <summary>
        /// 评论IP
        /// </summary>
    	[DataMember]
    	[DisplayName("评论IP")]
        public virtual string Ip
        {
            get;
            set;
        }
    
        /// <summary>
        /// 评论时间
        /// </summary>
    	[DataMember]
    	[DisplayName("评论时间")]
        public virtual System.DateTime AddTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 是否被删除
        /// </summary>
    	[DataMember]
    	[DisplayName("是否被删除")]
        public virtual int IsDelete
        {
            get;
            set;
        }
    
        /// <summary>
        /// 评论给分
        /// </summary>
    	[DataMember]
    	[DisplayName("评论给分")]
        public virtual int Fen
        {
            get;
            set;
        }
    
        /// <summary>
        /// 状态
        /// </summary>
    	[DataMember]
    	[DisplayName("状态")]
        public virtual int State
        {
            get;
            set;
        }

        #endregion
    }
}
