//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// 酒店评论表
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_HotelCommDtoValidate))]
    public partial class Sys_HotelCommDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// 评论ID号
        /// </summary>
    	[DataMember]
    	[DisplayName("评论ID号")]
        public virtual int CommID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 用户Id
        /// </summary>
    	[DataMember]
    	[DisplayName("用户Id")]
        public virtual int UserID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 用户名
        /// </summary>
    	[DataMember]
    	[DisplayName("用户名")]
        public virtual string UserName
        {
            get;
            set;
        }
    
        /// <summary>
        /// 酒店Id
        /// </summary>
    	[DataMember]
    	[DisplayName("酒店Id")]
        public virtual int HotelID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 评论内容
        /// </summary>
    	[DataMember]
    	[DisplayName("评论内容")]
        public virtual string Content
        {
            get;
            set;
        }
    
        /// <summary>
        /// 评论IP
        /// </summary>
    	[DataMember]
    	[DisplayName("评论IP")]
        public virtual string Ip
        {
            get;
            set;
        }
    
        /// <summary>
        /// 添加时间
        /// </summary>
    	[DataMember]
    	[DisplayName("添加时间")]
        public virtual System.DateTime AddTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// 评分
        /// </summary>
    	[DataMember]
    	[DisplayName("评分")]
        public virtual int Point
        {
            get;
            set;
        }

        #endregion
    }
}
