//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// Sys_AcData
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.Sys_AcDataDtoValidate))]
    public partial class Sys_AcDataDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// ID
        /// </summary>
    	[DataMember]
    	[DisplayName("ID")]
        public virtual int ID
        {
            get;
            set;
        }
    
        /// <summary>
        /// Ip
        /// </summary>
    	[DataMember]
    	[DisplayName("Ip")]
        public virtual string Ip
        {
            get;
            set;
        }
    
        /// <summary>
        /// AddTime
        /// </summary>
    	[DataMember]
    	[DisplayName("AddTime")]
        public virtual Nullable<System.DateTime> AddTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// DType
        /// </summary>
    	[DataMember]
    	[DisplayName("DType")]
        public virtual Nullable<int> DType
        {
            get;
            set;
        }
    
        /// <summary>
        /// ActivityID
        /// </summary>
    	[DataMember]
    	[DisplayName("ActivityID")]
        public virtual Nullable<int> ActivityID
        {
            get;
            set;
        }

        #endregion
    }
}
