//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace iPow.Domain.Dto
{
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    /// <summary>
    /// T_DailyRates
    /// </summary>
    [Serializable]
    [DataContract]
    [FluentValidation.Attributes.Validator(typeof(Validate.T_DailyRatesDtoValidate))]
    public partial class T_DailyRatesDto
    {
        #region Primitive Properties
    
        /// <summary>
        /// 每日价格ID
        /// </summary>
    	[DataMember]
    	[DisplayName("每日价格ID")]
        public virtual string DailyRatesID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 酒店编码
        /// </summary>
    	[DataMember]
    	[DisplayName("酒店编码")]
        public virtual string HotelCode
        {
            get;
            set;
        }
    
        /// <summary>
        /// 房间类型
        /// </summary>
    	[DataMember]
    	[DisplayName("房间类型")]
        public virtual string RoomType
        {
            get;
            set;
        }
    
        /// <summary>
        /// RateCode
        /// </summary>
    	[DataMember]
    	[DisplayName("RateCode")]
        public virtual string RateCode
        {
            get;
            set;
        }
    
        /// <summary>
        /// RatePlan
        /// </summary>
    	[DataMember]
    	[DisplayName("RatePlan")]
        public virtual string RatePlan
        {
            get;
            set;
        }
    
        /// <summary>
        /// 周期时间
        /// </summary>
    	[DataMember]
    	[DisplayName("周期时间")]
        public virtual Nullable<System.DateTime> PeriodDate
        {
            get;
            set;
        }
    
        /// <summary>
        /// 可用时间
        /// </summary>
    	[DataMember]
    	[DisplayName("可用时间")]
        public virtual Nullable<System.DateTime> AvailDate
        {
            get;
            set;
        }
    
        /// <summary>
        /// 状态
        /// </summary>
    	[DataMember]
    	[DisplayName("状态")]
        public virtual string AvStat
        {
            get;
            set;
        }
    
        /// <summary>
        /// 分配
        /// </summary>
    	[DataMember]
    	[DisplayName("分配")]
        public virtual Nullable<int> Allotment
        {
            get;
            set;
        }
    
        /// <summary>
        /// 开始时间
        /// </summary>
    	[DataMember]
    	[DisplayName("开始时间")]
        public virtual Nullable<int> LeadTime
        {
            get;
            set;
        }
    
        /// <summary>
        /// MinLOS
        /// </summary>
    	[DataMember]
    	[DisplayName("MinLOS")]
        public virtual Nullable<int> MinLOS
        {
            get;
            set;
        }
    
        /// <summary>
        /// MaxLOS
        /// </summary>
    	[DataMember]
    	[DisplayName("MaxLOS")]
        public virtual Nullable<int> MaxLOS
        {
            get;
            set;
        }
    
        /// <summary>
        /// 单价
        /// </summary>
    	[DataMember]
    	[DisplayName("单价")]
        public virtual Nullable<decimal> SingleRates
        {
            get;
            set;
        }
    
        /// <summary>
        /// 双价
        /// </summary>
    	[DataMember]
    	[DisplayName("双价")]
        public virtual Nullable<decimal> DoubleRates
        {
            get;
            set;
        }
    
        /// <summary>
        /// TripleRates
        /// </summary>
    	[DataMember]
    	[DisplayName("TripleRates")]
        public virtual Nullable<decimal> TripleRates
        {
            get;
            set;
        }
    
        /// <summary>
        /// QuadRates
        /// </summary>
    	[DataMember]
    	[DisplayName("QuadRates")]
        public virtual Nullable<decimal> QuadRates
        {
            get;
            set;
        }
    
        /// <summary>
        /// ExtraPersonRates
        /// </summary>
    	[DataMember]
    	[DisplayName("ExtraPersonRates")]
        public virtual Nullable<decimal> ExtraPersonRates
        {
            get;
            set;
        }
    
        /// <summary>
        /// ExtraChildRates
        /// </summary>
    	[DataMember]
    	[DisplayName("ExtraChildRates")]
        public virtual Nullable<decimal> ExtraChildRates
        {
            get;
            set;
        }
    
        /// <summary>
        /// Currency
        /// </summary>
    	[DataMember]
    	[DisplayName("Currency")]
        public virtual string Currency
        {
            get;
            set;
        }
    
        /// <summary>
        /// RefType
        /// </summary>
    	[DataMember]
    	[DisplayName("RefType")]
        public virtual string RefType
        {
            get;
            set;
        }
    
        /// <summary>
        /// RefID
        /// </summary>
    	[DataMember]
    	[DisplayName("RefID")]
        public virtual string RefID
        {
            get;
            set;
        }
    
        /// <summary>
        /// BreakfastAmount
        /// </summary>
    	[DataMember]
    	[DisplayName("BreakfastAmount")]
        public virtual Nullable<decimal> BreakfastAmount
        {
            get;
            set;
        }
    
        /// <summary>
        /// BreakfastNumber
        /// </summary>
    	[DataMember]
    	[DisplayName("BreakfastNumber")]
        public virtual Nullable<int> BreakfastNumber
        {
            get;
            set;
        }
    
        /// <summary>
        /// GUA
        /// </summary>
    	[DataMember]
    	[DisplayName("GUA")]
        public virtual string GUA
        {
            get;
            set;
        }
    
        /// <summary>
        /// CXL
        /// </summary>
    	[DataMember]
    	[DisplayName("CXL")]
        public virtual string CXL
        {
            get;
            set;
        }
    
        /// <summary>
        /// 状态
        /// </summary>
    	[DataMember]
    	[DisplayName("状态")]
        public virtual string Status
        {
            get;
            set;
        }
    
        /// <summary>
        /// 登陆
        /// </summary>
    	[DataMember]
    	[DisplayName("登陆")]
        public virtual string Sign
        {
            get;
            set;
        }
    
        /// <summary>
        /// LastModifierID
        /// </summary>
    	[DataMember]
    	[DisplayName("LastModifierID")]
        public virtual string LastModifierID
        {
            get;
            set;
        }
    
        /// <summary>
        /// LastModifyDate
        /// </summary>
    	[DataMember]
    	[DisplayName("LastModifyDate")]
        public virtual Nullable<System.DateTime> LastModifyDate
        {
            get;
            set;
        }
    
        /// <summary>
        /// CreatorID
        /// </summary>
    	[DataMember]
    	[DisplayName("CreatorID")]
        public virtual string CreatorID
        {
            get;
            set;
        }
    
        /// <summary>
        /// 创建时间
        /// </summary>
    	[DataMember]
    	[DisplayName("创建时间")]
        public virtual Nullable<System.DateTime> CreateDate
        {
            get;
            set;
        }

        #endregion
    }
}
