<?xml version="1.0" encoding="utf-8"?><Database Name="miaowsys" Class="MiaowSysModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=miaowsys;Persist Security Info=True;User ID=sa;MultipleActiveResultSets=True" SettingsObjectName="iPow.Infrastructure.Data.DataSys.Properties.Settings" SettingsPropertyName="miaowsysConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.m_user_info" Member="m_user_info">
    <Type Name="m_user_info">
      <Column Name="user_id" Type="System.String" DbType="NVarChar(40) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="profile_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="oldpassword" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="createdtime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="updatedtime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[remark]" Member="_remark" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="location" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="netaddress" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="state" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_sexual_orientation" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="user_relationship_status" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="birthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="blood_type" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="blogs_url" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MSN" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="QQ" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.m_profile_info" Member="m_profile_info">
    <Type Name="m_profile_info">
      <Column Name="profile_id" Type="System.String" DbType="NVarChar(40) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="user_id" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="profile_image_url" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="createdtime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.m_tag_info" Member="m_tag_info">
    <Type Name="m_tag_info">
      <Column Name="tag_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_id" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="tags" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="createdtime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>