#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18051
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPow.Infrastructure.Data.DataSys
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="miaowsys")]
	public partial class MiaowSysModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertm_user_info(m_user_info instance);
    partial void Updatem_user_info(m_user_info instance);
    partial void Deletem_user_info(m_user_info instance);
    partial void Insertm_profile_info(m_profile_info instance);
    partial void Updatem_profile_info(m_profile_info instance);
    partial void Deletem_profile_info(m_profile_info instance);
    partial void Insertm_tag_info(m_tag_info instance);
    partial void Updatem_tag_info(m_tag_info instance);
    partial void Deletem_tag_info(m_tag_info instance);
    #endregion
		
		public MiaowSysModelDataContext() : 
				base(global::iPow.Infrastructure.Data.DataSys.Properties.Settings.Default.miaowsysConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MiaowSysModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MiaowSysModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MiaowSysModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MiaowSysModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<m_user_info> m_user_info
		{
			get
			{
				return this.GetTable<m_user_info>();
			}
		}
		
		public System.Data.Linq.Table<m_profile_info> m_profile_info
		{
			get
			{
				return this.GetTable<m_profile_info>();
			}
		}
		
		public System.Data.Linq.Table<m_tag_info> m_tag_info
		{
			get
			{
				return this.GetTable<m_tag_info>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.m_user_info")]
	public partial class m_user_info : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _user_id;
		
		private int _profile_id;
		
		private string _user_name;
		
		private string _password;
		
		private string _oldpassword;
		
		private string _email;
		
		private char _gender;
		
		private System.DateTime _createdtime;
		
		private System.Nullable<System.DateTime> _updatedtime;
		
		private string @__remark;
		
		private string _location;
		
		private string _netaddress;
		
		private int _state;
		
		private System.Nullable<char> _user_sexual_orientation;
		
		private System.Nullable<char> _user_relationship_status;
		
		private System.Nullable<System.DateTime> _birthday;
		
		private string _blood_type;
		
		private string _blogs_url;
		
		private string _MSN;
		
		private string _QQ;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(string value);
    partial void Onuser_idChanged();
    partial void Onprofile_idChanging(int value);
    partial void Onprofile_idChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnoldpasswordChanging(string value);
    partial void OnoldpasswordChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OngenderChanging(char value);
    partial void OngenderChanged();
    partial void OncreatedtimeChanging(System.DateTime value);
    partial void OncreatedtimeChanged();
    partial void OnupdatedtimeChanging(System.Nullable<System.DateTime> value);
    partial void OnupdatedtimeChanged();
    partial void On_remarkChanging(string value);
    partial void On_remarkChanged();
    partial void OnlocationChanging(string value);
    partial void OnlocationChanged();
    partial void OnnetaddressChanging(string value);
    partial void OnnetaddressChanged();
    partial void OnstateChanging(int value);
    partial void OnstateChanged();
    partial void Onuser_sexual_orientationChanging(System.Nullable<char> value);
    partial void Onuser_sexual_orientationChanged();
    partial void Onuser_relationship_statusChanging(System.Nullable<char> value);
    partial void Onuser_relationship_statusChanged();
    partial void OnbirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnbirthdayChanged();
    partial void Onblood_typeChanging(string value);
    partial void Onblood_typeChanged();
    partial void Onblogs_urlChanging(string value);
    partial void Onblogs_urlChanged();
    partial void OnMSNChanging(string value);
    partial void OnMSNChanged();
    partial void OnQQChanging(string value);
    partial void OnQQChanged();
    #endregion
		
		public m_user_info()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="NVarChar(40) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profile_id", DbType="Int NOT NULL")]
		public int profile_id
		{
			get
			{
				return this._profile_id;
			}
			set
			{
				if ((this._profile_id != value))
				{
					this.Onprofile_idChanging(value);
					this.SendPropertyChanging();
					this._profile_id = value;
					this.SendPropertyChanged("profile_id");
					this.Onprofile_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oldpassword", DbType="NVarChar(50)")]
		public string oldpassword
		{
			get
			{
				return this._oldpassword;
			}
			set
			{
				if ((this._oldpassword != value))
				{
					this.OnoldpasswordChanging(value);
					this.SendPropertyChanging();
					this._oldpassword = value;
					this.SendPropertyChanged("oldpassword");
					this.OnoldpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="Char(1) NOT NULL")]
		public char gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdtime", DbType="DateTime NOT NULL")]
		public System.DateTime createdtime
		{
			get
			{
				return this._createdtime;
			}
			set
			{
				if ((this._createdtime != value))
				{
					this.OncreatedtimeChanging(value);
					this.SendPropertyChanging();
					this._createdtime = value;
					this.SendPropertyChanged("createdtime");
					this.OncreatedtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> updatedtime
		{
			get
			{
				return this._updatedtime;
			}
			set
			{
				if ((this._updatedtime != value))
				{
					this.OnupdatedtimeChanging(value);
					this.SendPropertyChanging();
					this._updatedtime = value;
					this.SendPropertyChanged("updatedtime");
					this.OnupdatedtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[remark]", Storage="__remark", DbType="NVarChar(200)")]
		public string _remark
		{
			get
			{
				return this.@__remark;
			}
			set
			{
				if ((this.@__remark != value))
				{
					this.On_remarkChanging(value);
					this.SendPropertyChanging();
					this.@__remark = value;
					this.SendPropertyChanged("_remark");
					this.On_remarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string location
		{
			get
			{
				return this._location;
			}
			set
			{
				if ((this._location != value))
				{
					this.OnlocationChanging(value);
					this.SendPropertyChanging();
					this._location = value;
					this.SendPropertyChanged("location");
					this.OnlocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_netaddress", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string netaddress
		{
			get
			{
				return this._netaddress;
			}
			set
			{
				if ((this._netaddress != value))
				{
					this.OnnetaddressChanging(value);
					this.SendPropertyChanging();
					this._netaddress = value;
					this.SendPropertyChanged("netaddress");
					this.OnnetaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="Int NOT NULL")]
		public int state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_sexual_orientation", DbType="Char(1)")]
		public System.Nullable<char> user_sexual_orientation
		{
			get
			{
				return this._user_sexual_orientation;
			}
			set
			{
				if ((this._user_sexual_orientation != value))
				{
					this.Onuser_sexual_orientationChanging(value);
					this.SendPropertyChanging();
					this._user_sexual_orientation = value;
					this.SendPropertyChanged("user_sexual_orientation");
					this.Onuser_sexual_orientationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_relationship_status", DbType="Char(1)")]
		public System.Nullable<char> user_relationship_status
		{
			get
			{
				return this._user_relationship_status;
			}
			set
			{
				if ((this._user_relationship_status != value))
				{
					this.Onuser_relationship_statusChanging(value);
					this.SendPropertyChanging();
					this._user_relationship_status = value;
					this.SendPropertyChanged("user_relationship_status");
					this.Onuser_relationship_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="DateTime")]
		public System.Nullable<System.DateTime> birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this.OnbirthdayChanging(value);
					this.SendPropertyChanging();
					this._birthday = value;
					this.SendPropertyChanged("birthday");
					this.OnbirthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_blood_type", DbType="Char(2)")]
		public string blood_type
		{
			get
			{
				return this._blood_type;
			}
			set
			{
				if ((this._blood_type != value))
				{
					this.Onblood_typeChanging(value);
					this.SendPropertyChanging();
					this._blood_type = value;
					this.SendPropertyChanged("blood_type");
					this.Onblood_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_blogs_url", DbType="NVarChar(100)")]
		public string blogs_url
		{
			get
			{
				return this._blogs_url;
			}
			set
			{
				if ((this._blogs_url != value))
				{
					this.Onblogs_urlChanging(value);
					this.SendPropertyChanging();
					this._blogs_url = value;
					this.SendPropertyChanged("blogs_url");
					this.Onblogs_urlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSN", DbType="NVarChar(100)")]
		public string MSN
		{
			get
			{
				return this._MSN;
			}
			set
			{
				if ((this._MSN != value))
				{
					this.OnMSNChanging(value);
					this.SendPropertyChanging();
					this._MSN = value;
					this.SendPropertyChanged("MSN");
					this.OnMSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QQ", DbType="NChar(10)")]
		public string QQ
		{
			get
			{
				return this._QQ;
			}
			set
			{
				if ((this._QQ != value))
				{
					this.OnQQChanging(value);
					this.SendPropertyChanging();
					this._QQ = value;
					this.SendPropertyChanged("QQ");
					this.OnQQChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.m_profile_info")]
	public partial class m_profile_info : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _profile_id;
		
		private string _user_id;
		
		private string _profile_image_url;
		
		private System.DateTime _createdtime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onprofile_idChanging(string value);
    partial void Onprofile_idChanged();
    partial void Onuser_idChanging(string value);
    partial void Onuser_idChanged();
    partial void Onprofile_image_urlChanging(string value);
    partial void Onprofile_image_urlChanged();
    partial void OncreatedtimeChanging(System.DateTime value);
    partial void OncreatedtimeChanged();
    #endregion
		
		public m_profile_info()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profile_id", DbType="NVarChar(40) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string profile_id
		{
			get
			{
				return this._profile_id;
			}
			set
			{
				if ((this._profile_id != value))
				{
					this.Onprofile_idChanging(value);
					this.SendPropertyChanging();
					this._profile_id = value;
					this.SendPropertyChanged("profile_id");
					this.Onprofile_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profile_image_url", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string profile_image_url
		{
			get
			{
				return this._profile_image_url;
			}
			set
			{
				if ((this._profile_image_url != value))
				{
					this.Onprofile_image_urlChanging(value);
					this.SendPropertyChanging();
					this._profile_image_url = value;
					this.SendPropertyChanged("profile_image_url");
					this.Onprofile_image_urlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdtime", DbType="DateTime NOT NULL")]
		public System.DateTime createdtime
		{
			get
			{
				return this._createdtime;
			}
			set
			{
				if ((this._createdtime != value))
				{
					this.OncreatedtimeChanging(value);
					this.SendPropertyChanging();
					this._createdtime = value;
					this.SendPropertyChanged("createdtime");
					this.OncreatedtimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.m_tag_info")]
	public partial class m_tag_info : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tag_id;
		
		private string _user_id;
		
		private string _tags;
		
		private System.Nullable<System.DateTime> _createdtime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontag_idChanging(int value);
    partial void Ontag_idChanged();
    partial void Onuser_idChanging(string value);
    partial void Onuser_idChanged();
    partial void OntagsChanging(string value);
    partial void OntagsChanged();
    partial void OncreatedtimeChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedtimeChanged();
    #endregion
		
		public m_tag_info()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tag_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tag_id
		{
			get
			{
				return this._tag_id;
			}
			set
			{
				if ((this._tag_id != value))
				{
					this.Ontag_idChanging(value);
					this.SendPropertyChanging();
					this._tag_id = value;
					this.SendPropertyChanged("tag_id");
					this.Ontag_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="NVarChar(40)")]
		public string user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tags", DbType="NVarChar(50)")]
		public string tags
		{
			get
			{
				return this._tags;
			}
			set
			{
				if ((this._tags != value))
				{
					this.OntagsChanging(value);
					this.SendPropertyChanging();
					this._tags = value;
					this.SendPropertyChanged("tags");
					this.OntagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> createdtime
		{
			get
			{
				return this._createdtime;
			}
			set
			{
				if ((this._createdtime != value))
				{
					this.OncreatedtimeChanging(value);
					this.SendPropertyChanging();
					this._createdtime = value;
					this.SendPropertyChanged("createdtime");
					this.OncreatedtimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
